SET @extractstart = '2016-02-21';
SET @extractend = '2016-03-01';

SELECT 
    so.order_nr,
    soi.bob_id_sales_order_item,
    soi.unit_price,
    soi.paid_price,
    soi.shipping_surcharge,
    soi.coupon_money_value,
    soi.cart_rule_discount,
    so.coupon_code,
    soi.sku,
    so.created_at 'order_date',
    sois.name 'item_status',
    so.payment_method,
    sfom.origin 'home_zone',
    dist.name 'dest_district',
    city.name 'dest_city',
    reg.name 'dest_region',
    sup.type 'seller_type',
    sup.name 'seller_name',
    sel.short_code 'sc_seller_id',
    sel.tax_class
FROM
    oms_live.ims_sales_order so
        LEFT JOIN
    oms_live.ims_sales_order_item soi ON soi.fk_sales_order = so.id_sales_order
        LEFT JOIN
    oms_live.ims_sales_order_item_status sois ON soi.fk_sales_order_item_status = sois.id_sales_order_item_status
        LEFT JOIN
    oms_live.ims_sales_order_address soa ON so.fk_sales_order_address_shipping = soa.id_sales_order_address
        LEFT JOIN
    oms_live.ims_customer_address_region dist ON soa.fk_customer_address_region = dist.id_customer_address_region
        LEFT JOIN
    oms_live.ims_customer_address_region city ON dist.fk_customer_address_region = city.id_customer_address_region
        LEFT JOIN
    oms_live.ims_customer_address_region reg ON city.fk_customer_address_region = reg.id_customer_address_region
        LEFT JOIN
    bob_live.supplier sup ON soi.bob_id_supplier = sup.id_supplier
        LEFT JOIN
    bob_live.supplier_address sa ON sup.id_supplier = sa.fk_supplier
        AND sa.address_type = 'standard'
        LEFT JOIN
    bob_live.shipping_fee_origin_mapping sfom ON sa.fk_country_region = sfom.fk_country_region
        LEFT JOIN
    screport.seller sel ON sup.name = sel.name
WHERE
    so.created_at >= @extractstart
        AND so.created_at < @extractend
        AND dist.name IN ('Abiansemal',
'Mengwi',
'Petang',
'Bangli',
'Kintamani',
'Susut',
'Tembuku',
'Banjar Buleleng',
'Buleleng',
'Busungbiu',
'Gerokgak',
'Kubutambahan',
'Sawan',
'Seririt',
'Sukasada',
'Tejakula',
'Belah Batuh (Blahbatuh)',
'Gianyar',
'Payangan',
'Sukawati',
'Tampak Siring',
'Tegal lalang',
'Ubud',
'Jembrana',
'Melaya',
'Mendoyo',
'Negara',
'Pekutatan',
'Abang',
'Bebandem',
'KarangAsem',
'Kubu',
'Manggis',
'Rendang',
'Selat',
'Sidemen',
'Banjarangkan',
'Dawan',
'Klungkung',
'Nusapenida',
'Baturiti',
'Kediri Tabanan',
'Kerambitan',
'Marga',
'Penebel',
'Pupuan',
'Selemadeg',
'Selemadeg Barat',
'Selemadeg Timur',
'Tabanan',
'Denpasar Barat',
'Denpasar Selatan',
'Denpasar Timur',
'Denpasar Utara',
'Bakam',
'Mendo Barat',
'Merawang',
'Pemali',
'Puding Besar',
'Riau Silip',
'Air Gegas',
'Lepar Pongok',
'Payung',
'Pulau Besar',
'Simpang Rimba',
'Tukak Sadai',
'Lubuk Besar',
'Namang',
'Pangkalan Baru',
'Simpang Katis',
'Sungai Selan',
'Badau Belitung',
'Membalong',
'Selat Nasik',
'Sijuk',
'Dendang Bangka Belitung',
'Gantung',
'Kelapa Kampit',
'Bukit Intan',
'Gerunggang',
'Pangkal Balam',
'Rangkui',
'Taman Sari',
'Banjarsari',
'Bayah',
'Bojongmanik',
'Cibadak',
'Cibeber Lebak',
'Cigemblong',
'Cihara',
'Cijaku',
'Cikulur',
'Cileles',
'Cilograng',
'Cimarga',
'Cipanas Lebak',
'Cirinten',
'Curugbitung',
'Gunung Kencana',
'Kalanganyar',
'Lebakgedong',
'Leuwidamar',
'Maja Lebak',
'Malingping',
'Muncang',
'Panggarangan',
'Sajira',
'Sobang',
'Wanasalam',
'Warunggunung',
'Angsana',
'Banjar',
'Bojong Pandeglang',
'Cadasari',
'Carita',
'Cibaliung',
'Cibitung Pandeglang',
'Cigeulis',
'Cikeudal (Cikedal)',
'Cikeusik',
'Cimanggu Pandeglang',
'Cimanuk',
'Cipeucang',
'Cisata',
'Jiput',
'Kaduhejo',
'Karang Tanjung',
'Koroncong',
'Labuan',
'Majasari',
'Mandalawangi',
'Mekarjaya',
'Menes',
'Munjul',
'Pagelaran Pandeglang',
'Pandeglang',
'Panimbang',
'Patia',
'Picung',
'Pulosari',
'Saketi',
'Sindangresmi',
'Sobang',
'Sukaresmi',
'Sumur',
'Anyer/anyar',
'Bandung',
'Baros',
'Binuang Serang',
'Bojonegara',
'Carenang',
'Cikande',
'Cikeusal',
'Cinangka',
'Ciomas',
'Ciruas',
'Gunungsari',
'Jawilan',
'Kibin',
'Kopo',
'Kragilan',
'Kramatwatu',
'Mancak',
'Pabuaran Serang',
'Padarincang',
'Pamarayan',
'Petir',
'Pontang',
'Pulo Ampel',
'Tanara',
'Tirtayasa',
'Tunjung Teja',
'Waringin Kurung',
'Balaraja',
'Cikupa',
'Cisauk',
'Cisoka',
'Curug Tangerang',
'Gunung Kaler',
'Jambe',
'Jayanti',
'Kelapa Dua',
'Kemiri Tangerang',
'Kosambi',
'Kresek',
'Kronjo',
'Legok',
'Mauk',
'Mekar Baru',
'Pagedangan',
'Pakuhaji',
'Panongan',
'Pasar Kemis',
'Rajeg',
'Sepatan',
'Sepatan Timur',
'Sindang Jaya',
'Solear',
'Sukadiri',
'Sukamulya',
'Teluknaga',
'Tigaraksa',
'Cibeber',
'Cilegon',
'Citangkil',
'Ciwandan',
'Gerogol',
'Jombang',
'Pulomerak',
'Purwakarta Cilegon',
'Cipocok Jaya',
'Curug',
'Kasemen',
'Serang',
'Taktakan',
'Walantaka',
'Batuceper',
'Benda',
'Cibodas',
'Ciledug',
'Cipondoh',
'Jatiuwung',
'Karang Tengah',
'Karawaci',
'Larangan Tangerang',
'Neglasari',
'Periuk',
'Pinang (Penang)',
'Tangerang',
'Ciputat',
'Ciputat Timur',
'Pamulang',
'Pondok Aren',
'Serpong',
'Serpong Utara',
'Setu',
'Air Nipis',
'Bunga Mas',
'Kedurang',
'Kedurang Ilir',
'Manna',
'Pasar Manna',
'Pino',
'Pinoraya',
'Seginim',
'Ulu Manna',
'Karang Tinggi',
'Pagar Jati',
'Pematang Tiga',
'Pondok Kelapa',
'Taba Penanjung',
'Talang Empat',
'Enggano',
'Napal Putih',
'Kaur Selatan',
'Kaur Tengah',
'Kaur Utara',
'Kelam Tengah',
'Kinal',
'Luas',
'Lungkang Kule',
'Maje',
'Muara Sahung',
'Nasal',
'Padang Guci Hilir',
'Padang Guci Hulu',
'Semidang Gumai (Gumay)',
'Tanjung Kemuning',
'Tetap (Muara Tetap)',
'Bermani Ilir',
'Kebawetan (Kabawetan)',
'Merigi',
'Muara Kemumu',
'Seberang Musi',
'Tebat Karai',
'Ujan Mas',
'Lebong Atas',
'Lebong Selatan',
'Lebong Tengah',
'Lebong Utara',
'Rimbo Pengadang',
'Air Dikit',
'Air Majunto',
'Air Rami',
'Lubuk Pinang',
'Malin Deman',
'Muko-Muko Selatan',
'Muko-muko Utara',
'Penarik',
'Pondok Suguh',
'Selagan Raya',
'Sungai Rumbai',
'Teramang Jaya',
'Teras Terunjam',
'V Koto Kp Dalam',
'Xiv Koto',
'Bermani Ulu',
'Bermani Ulu Raya',
'Binduriang',
'Curup Selatan',
'Curup Tengah',
'Curup Timur',
'Curup Utara',
'Kota Padang',
'Padang Ulak Tanding',
'Selupu Rejang',
'Sindang Beliti Ilir',
'Sindang Beliti Ulu',
'Sindang Daratan',
'Sindang Kelingi',
'Air Periukan',
'Ilir Talo',
'Lubuk Sandi',
'Seluma',
'Seluma Barat',
'Seluma Selatan',
'Seluma Timur',
'Seluma Utara',
'Semidang Alas',
'Semidang Alas Maras',
'Sukaraja Seluma',
'Talo',
'Talo Kecil',
'Ulu Talo',
'Gading Cempaka',
'Kampung Melayu',
'Muara Bangka Hulu',
'Ratu Agung',
'Ratu Samban',
'Selebar',
'Sungai Serut',
'Teluk Segara',
'Gedang Sari',
'Girisubo',
'Karangmojo',
'Ngawen',
'Nglipar',
'Paliyan',
'Panggang',
'Patuk',
'Playen',
'Ponjong',
'Purwosari',
'Rongkop',
'Sapto Sari',
'Semanu',
'Semin',
'Tanjungsari',
'Tepus',
'Galur',
'Girimulyo',
'Kalibawang',
'Kokap',
'Lendah',
'Nanggulan',
'Panjatan',
'Pengasih',
'Samigaluh',
'Sentolo',
'Temon',
'Danurejan',
'Gedong Tengen',
'Gondokusuman',
'Gondomanan',
'Jetis',
'Kotagede',
'Kraton',
'Mantrijeron',
'Mergangsan',
'Ngampilan',
'Pakualaman',
'Tegalrejo',
'Umbulharjo',
'Wirobrajan',
'Kepulauan Seribu Selatan',
'Kepulauan Seribu Utara',
'Cengkareng',
'Grogol Petamburan',
'Kalideres',
'Kebon Jeruk',
'Kembangan',
'Palmerah',
'Taman Sari',
'Tambora Jakarta',
'Cempaka Putih',
'Gambir',
'Johar Baru',
'Kemayoran',
'Menteng',
'Sawah Besar',
'Senen',
'Tanah Abang',
'Cilandak',
'Jagakarsa',
'Kebayoran Baru',
'Kebayoran Lama',
'Mampang Prapatan',
'Pancoran',
'Pasar Minggu',
'Pesanggrahan',
'Setiabudi',
'Tebet',
'Cakung',
'Cipayung',
'Ciracas',
'Duren Sawit',
'Jatinegara',
'Kramat Jati',
'Makasar Jakarta',
'Matraman',
'Pasar Rebo',
'Pulo Gadung',
'Cilincing',
'Kelapa Gading',
'Koja',
'Pademangan',
'Penjaringan',
'Tanjung Priok',
'Botumoita (Botumoito)',
'Dulupi',
'Mananggu',
'Paguyaman',
'Paguyaman Pantai',
'Wonosari',
'Bone',
'Bone Raya',
'Bonepantai',
'Botu Pingge',
'Bulango Selatan',
'Bulango Timur',
'Bulango Ulu',
'Bulango Utara',
'Bulawa',
'Kabila',
'Kabila Bone',
'Suwawa',
'Suwawa Selatan',
'Suwawa Tengah',
'Suwawa Timur',
'Tapa',
'Tilongkabila',
'Asparaga',
'Batudaa',
'Batudaa Pantai',
'Biluhu',
'Boliohuto (Boliyohuto)',
'Bongomeme',
'Mootilango',
'Pulubala',
'Tabongo',
'Telaga Biru',
'Telaga Jaya',
'Tibawa',
'Tilango',
'Tolangohula',
'Anggrek',
'Atinggola',
'Sumalata',
'Tolinggula',
'Buntulia',
'Dengilo',
'Duhiadaa',
'Lemito',
'Marisa',
'Paguat',
'Patilanggio',
'Popayato',
'Popayato Barat',
'Popayato Timur',
'Randangan',
'Taluduti',
'Wanggarasi',
'Dungingi',
'Kota Barat',
'Kota Selatan',
'Kota Tengah',
'Kota Timur',
'Kota Utara',
'Bajubang',
'Batin Xxiv',
'Maro Sebo Ilir',
'Maro Sebo Ulu',
'Mersam',
'Muara Tembesi',
'Pemayung',
'Jujuhan',
'Gunung Raya',
'Kayu Aro',
'Jangkat',
'Sungai Manau',
'Jambi Luar Kota',
'Kumpeh',
'Kumpeh Ulu',
'Maro Sebo',
'Mestong',
'Sekernan',
'Sungai Bahar',
'Sungai Gelam',
'Batang Asai',
'Batang Asam',
'Betara',
'Bram Itam',
'Kuala Betara',
'Merlung',
'Muara Papalik',
'Pengabuan',
'Renah Mendaluh',
'Seberang Kota',
'Senyerang',
'Tebing Tinggi',
'Tungkal Ilir',
'Tungkal Ulu',
'Rantau Rasau',
'Muara Tabir',
'Rimbo Bujang',
'Rimbo Ilir',
'Rimbo Ulu',
'Serai Serumpun',
'Sumay',
'Tebo Ilir',
'Tebo Tengah',
'Tebo Ulu',
'Tengah Ilir',
'Vii Koto',
'Vii Koto Ilir',
'Danau Teluk',
'Jambi Selatan',
'Jambi Timur',
'Jelutung',
'Kota Baru',
'Pasar Jambi',
'Pelayangan',
'Telanaipura',
'Hamparan Rawang',
'Kumun Debai',
'Pesisir Bukit',
'Sungai Penuh',
'Tanah Kampung',
'Arjasari',
'Baleendah',
'Banjaran',
'Bojongsoang',
'Cangkuang',
'Cicalengka',
'Cikancung',
'Cilengkrang',
'Cileunyi',
'Cimaung',
'Cimeunyan',
'Ciparay',
'Ciwidey',
'Dayeuhkolot',
'Ibun',
'Katapang',
'Kertasari',
'Kutawaringin',
'Majalaya',
'Margaasih',
'Margahayu',
'Nagreg',
'Pacet',
'Pameungpeuk',
'Pangalengan',
'Paseh',
'Pasirjambu',
'Ranca Bali',
'Rancaekek',
'Solokan Jeruk',
'Soreang',
'Batujajar',
'Cihampelas',
'Cikalong Wetan',
'Cililin',
'Cipatat',
'Cipeundeuy',
'Cipongkor',
'Cisarua',
'Gununghalu',
'Lembang',
'Ngamprah',
'Padalarang',
'Parongpong',
'Rongga',
'Sindangkerta',
'Babelan',
'Bojongmangu',
'Cabangbungin',
'Cibarusah',
'Cibitung',
'Cikarang Barat',
'Cikarang Pusat',
'Cikarang Selatan',
'Cikarang Timur',
'Cikarang Utara',
'Karangbahagia',
'Kedung Waringin',
'Muara Gembong',
'Pebayuran',
'Serang Baru',
'Setu',
'Sukakarya',
'Sukatani',
'Sukawangi',
'Tambelang',
'Tambun Selatan',
'Tambun Utara',
'Tarumajaya',
'Babakan Madang',
'Bojonggede',
'Caringin',
'Cariu',
'Ciampea',
'Ciawi',
'Cibinong',
'Cibungbulang',
'Cigombong',
'Cigudeg',
'Cijeruk',
'Cileungsi',
'Ciomas',
'Cisarua',
'Ciseeng',
'Citeureup',
'Dramaga',
'Gunung Putri',
'Gunung Sindur',
'Jasinga',
'Jonggol',
'Kemang',
'Klapa Nunggal (Kelapa Nunggal)',
'Leuwiliang',
'Leuwisadeng',
'Megamendung',
'Nanggung',
'Pamijahan',
'Parung',
'Parung Panjang',
'Ranca Bungur',
'Rumpin',
'Sukajaya',
'Sukamakmur',
'Sukaraja',
'Tajurhalang',
'Tamansari',
'Tanjungsari',
'Tenjo',
'Tenjolaya',
'Banjarsari',
'Baregbeg',
'Ciamis',
'Cidolog',
'Cigugur',
'Cihaurbeuti',
'Cijeungjing',
'Cijulang',
'Cikoneng',
'Cimaragas',
'Cimerak',
'Cipaku',
'Cisaga',
'Jatinagara',
'Kalipucang',
'Kawali',
'Lakbok',
'Langkaplancar',
'Lumbung',
'Mangunjaya',
'Padaherang',
'Pamarican',
'Panawangan',
'Pangandaran',
'Panjalu',
'Panjalu Utara',
'Panumbangan',
'Parigi',
'Purwadadi',
'Rajadesa',
'Rancah',
'Sadananya',
'Sidamulih',
'Sindangkasih',
'Sukadana',
'Sukamantri',
'Tambaksari',
'Agrabinta',
'Bojongpicung',
'Campaka',
'Campaka Mulya',
'Cibeber',
'Cibinong',
'Cidaun',
'Cijati',
'Cikadu',
'Cikalongkulon',
'Cilaku',
'Cipanas',
'Ciranjang',
'Cugenang',
'Gekbrong',
'Haurwangi',
'Kadupandak',
'Karangtengah',
'Leles',
'Mande',
'Naringgul',
'Pacet',
'Pagelaran',
'Pasirkuda',
'Sindangbarang',
'Sukaluyu',
'Sukanagara',
'Sukaresmi',
'Takokak',
'Tanggeung',
'Warungkondang',
'Astanajapura',
'Babakan',
'Beber',
'Ciledug',
'Gebang',
'Greged (Greget)',
'Gunung Jati (Cirebon Utara)',
'Jamblang',
'Karangsembung',
'Karangwareng',
'Lemahabang',
'Losari',
'Pabedilan',
'Pabuaran',
'Palimanan',
'Pangenan',
'Panguragan',
'Sedong',
'Suranenggala',
'Talun (Cirebon Selatan)',
'Waled',
'Banjarwangi',
'Banyuresmi',
'Bayongbong',
'Blubur Limbangan',
'Bungbulang',
'Caringin',
'Cibalong',
'Cibatu',
'Cibiuk',
'Cigedug',
'Cihurip',
'Cikajang',
'Cikelet',
'Cilawu',
'Cisewu',
'Cisompet',
'Cisurupan',
'Kadungora',
'Karangpawitan',
'Karangtengah',
'Kersamanah',
'Leles',
'Leuwigoong',
'Malangbong',
'Mekarmukti',
'Pakenjeng',
'Pameungpeuk',
'Pamulihan',
'Pangatikan',
'Pasirwangi',
'Peundeuy',
'Samarang',
'Selaawi',
'Singajaya',
'Sucinaraja',
'Sukaresmi',
'Sukawening',
'Talegong',
'Tarogong Kaler',
'Tarogong Kidul',
'Wanaraja',
'Anjatan',
'Arahan',
'Balongan',
'Bangodua',
'Bongas',
'Cantigi',
'Cikedung',
'Gabuswetan',
'Gantar',
'Haurgeulis',
'Juntinyuat',
'Kandanghaur',
'Karangampel',
'Kedokan Bunder',
'Kertasemaya',
'Krangkeng',
'Kroya',
'Lelea',
'Lohbener',
'Losarang',
'Pasekan',
'Patrol',
'Sindang',
'Sliyeg',
'Sukagumiwang',
'Sukra',
'Trisi/terisi',
'Tukdana',
'Widasari',
'Banyusari',
'Batujaya',
'Cibuaya',
'Cilamaya Kulon',
'Cilamaya Wetan',
'Cilebar',
'Jayakerta',
'Kutawaluya',
'Pakisjaya',
'Pangkalan',
'Pedes',
'Tegalwaru',
'Tempuran',
'Tirtajaya',
'Ciawigebang',
'Cibeureum',
'Cibingbin',
'Cidahu',
'Cigandamekar',
'Cigugur',
'Cilebak',
'Cilimus',
'Cimahi',
'Ciniru',
'Cipicung',
'Ciwaru',
'Darma',
'Garawangi',
'Hantara',
'Jalaksana',
'Japara',
'Kadugede',
'Kalimanggis',
'Karangkancana',
'Kramat Mulya',
'Lebakwangi',
'Luragung',
'Maleber',
'Mandirancan',
'Nusaherang',
'Pancalang',
'Pasawahan',
'Selajambe',
'Sindangagung',
'Subang',
'Argapura',
'Banjaran',
'Bantarujeg',
'Cigasong',
'Cikijing',
'Cingambul',
'Dawuan',
'Jatitujuh',
'Kasokandel',
'Kertajati',
'Lemahsugih',
'Leuwimunding',
'Ligung',
'Maja',
'Malausma',
'Palasah',
'Panyingkiran',
'Rajagaluh',
'Sindang',
'Sindangwangi',
'Sukahaji',
'Sumberjaya',
'Talaga',
'Babakancikao',
'Bojong',
'Bungursari',
'Campaka',
'Cibatu',
'Darangdan',
'Jatiluhur',
'Kiarapedes',
'Maniis',
'Pasawahan',
'Plered',
'Pondoksalam',
'Sukasari',
'Sukatani',
'Tegal Waru',
'Wanayasa',
'Binong',
'Blanakan',
'Ciasem',
'Ciater',
'Cibogo',
'Cijambe',
'Cikaum',
'Cipeundeuy',
'Cipunagara',
'Cisalak',
'Compreng',
'Dawuan',
'Jalancagak',
'Kalijati',
'Kasomalang',
'Legonkulon',
'Pabuaran',
'Pagaden',
'Pagaden Barat',
'Pamanukan',
'Patokbeusi',
'Purwadadi',
'Pusakajaya',
'Pusakanagara',
'Sagalaherang',
'Serangpanjang',
'Sukasari',
'Tambakdahan',
'Tanjungsiang',
'Bantargadung',
'Bojong Genteng',
'Caringin',
'Ciambar',
'Cibitung',
'Cicantayan',
'Cicurug',
'Cidadap',
'Cidahu',
'Cidolog',
'Ciemas',
'Cikakak',
'Cikembar',
'Cikidang',
'Cimanggu',
'Ciracap',
'Cireunghas',
'Cisolok',
'Curugkembar',
'Geger Bitung',
'Gunung Guruh',
'Jampang Kulon',
'Jampang Tengah',
'Kabandungan',
'Kadudampit',
'Kalapa Nunggal',
'Kali Bunder',
'Kebonpedes',
'Lengkong',
'Nagrak',
'Nyalindung',
'Pabuaran',
'Parakan Salak',
'Parung Kuda',
'Purabaya',
'Sagaranten',
'Simpenan',
'Sukalarang',
'Surade',
'Tegal Buleud',
'Waluran',
'Warung Kiara',
'Buahdua',
'Cibugel',
'Cimalaka',
'Cimanggung',
'Cisarua',
'Cisitu',
'Conggeang',
'Darmaraja',
'Ganeas',
'Jatigede',
'Jatinunggal',
'Pamulihan',
'Paseh',
'Rancakalong',
'Situraja',
'Sukasari',
'Surian',
'Tanjungkerta',
'Tanjungmedar',
'Tanjungsari',
'Tomo',
'Ujungjaya',
'Wado',
'Bantarkalong',
'Bojongasih',
'Bojonggambir',
'Ciawi',
'Cibalong',
'Cigalontang',
'Cikalong',
'Cikatomas',
'Cineam',
'Cipatujah',
'Cisayong',
'Culamega',
'Gunung Tanjung',
'Jamanis',
'Jatiwaras',
'Kadipaten',
'Karang Jaya',
'Karangnunggal',
'Leuwisari',
'Mangunreja',
'Manonjaya',
'Padakembang',
'Pagerageung',
'Pancatengah',
'Parungponteng',
'Puspahiang',
'Rajapolah',
'Salawu',
'Salopa',
'Sariwangi',
'Sodonghilir',
'Sukahening',
'Sukaraja',
'Sukarame',
'Sukaratu',
'Sukaresik',
'Tanjungjaya',
'Taraju',
'Andir',
'Antapani (Cicadas)',
'Arcamanik',
'Astana Anyar',
'Babakan Ciparay',
'Bandung Kidul',
'Bandung Kulon',
'Bandung Wetan',
'Batununggal',
'Bojongloa Kaler',
'Bojongloa Kidul',
'Buahbatu (Margacinta)',
'Cibeunying Kaler',
'Cibeunying Kidul',
'Cibiru',
'Cicendo',
'Cidadap',
'Cinambo',
'Coblong',
'Gedebage',
'Kiaracondong',
'Lengkong',
'Mandalajati',
'Panyileukan',
'Rancasari',
'Regol',
'Sukajadi',
'Sukasari',
'Sumur Bandung',
'Ujung Berung',
'Banjar',
'Langensari',
'Pataruman',
'Purwaharja',
'Bantar Gebang',
'Bekasi Barat',
'Bekasi Selatan',
'Bekasi Timur',
'Bekasi Utara',
'Jati Sampurna',
'Jatiasih',
'Medan Satria',
'Mustika Jaya',
'Pondok Gede',
'Pondok Melati',
'Rawalumbu',
'Bogor Barat - Kota',
'Bogor Selatan - Kota',
'Bogor Tengah - Kota',
'Bogor Timur - Kota',
'Bogor Utara - Kota',
'Tanah Sereal',
'Cimahi Selatan',
'Cimahi Tengah',
'Cimahi Utara',
'Harjamukti',
'Kejaksan',
'Kesambi',
'Lemahwungkuk',
'Pekalipan',
'Beji',
'Cimanggis',
'Limo',
'Pancoran Mas',
'Sawangan',
'Sukmajaya',
'Baros',
'Cibeureum',
'Cikole',
'Citamiang',
'Gunung Puyuh',
'Lembursitu',
'Warudoyong',
'Bungursari',
'Cibeureum',
'Cihideung',
'Cipedes',
'Indihiang',
'Kawalu',
'Mangkubumi',
'Purbaratu',
'Tamansari',
'Tawang',
'Banjarmangu',
'Batur',
'Bawang',
'Kalibening',
'Karangkobar',
'Madukara',
'Mandiraja',
'Pagedongan',
'Pagentan',
'Pandanarum',
'Pejawaran',
'Punggelan',
'Purwonegoro',
'Purworejo Klampok',
'Rakit',
'Sigaluh',
'Susukan',
'Wanadadi (Wonodadi)',
'Wanayasa',
'Ajibarang',
'Banyumas',
'Baturaden',
'Cilongok',
'Gumelar',
'Jatilawang',
'Kalibagor',
'Karanglewas',
'Kebasen',
'Kedung Banteng',
'Kembaran',
'Kemranjen',
'Lumbir',
'Patikraja',
'Pekuncen',
'Purwojati',
'Rawalo',
'Sokaraja',
'Somagede',
'Sumbang',
'Sumpiuh',
'Tambak',
'Wangon',
'Bandar',
'Banyuputih',
'Batang',
'Bawang',
'Blado',
'Gringsing',
'Kandeman',
'Limpung',
'Pecalungan',
'Reban',
'Subah',
'Tersono',
'Tulis',
'Warungasem',
'Wonotunggal',
'Banjarejo',
'Blora Kota',
'Bogorejo',
'Cepu',
'Japah',
'Jati',
'Jepon',
'Jiken',
'Kedungtuban',
'Kradenan',
'Kunduran',
'Ngawen',
'Randublatung',
'Sambong',
'Todanan',
'Tunjungan',
'Ampel',
'Andong',
'Banyudono',
'Cepogo',
'Juwangi',
'Karanggede',
'Kemusu',
'Klego',
'Mojosongo',
'Musuk',
'Ngemplak',
'Nogosari',
'Sambi',
'Sawit',
'Selo',
'Simo',
'Teras',
'Wonosegoro',
'Banjarharjo',
'Bantarkawung',
'Bulakamba',
'Jatibarang',
'Kersana',
'Ketanggungan',
'Larangan',
'Losari',
'Paguyangan',
'Salem',
'Sirampog',
'Songgom',
'Tanjung',
'Tonjong',
'Wanasari',
'Adipala',
'Bantarsari',
'Binangun',
'Cimanggu',
'Cipari',
'Dayeuhluhur',
'Gandrungmangu',
'Jeruklegi',
'Kampung Laut',
'Karangpucung',
'Kawunganten',
'Kedungreja',
'Kesugihan',
'Kroya',
'Majenang',
'Maos',
'Nusawungu',
'Patimuan',
'Sampang',
'Sidareja',
'Wanareja',
'Bonang',
'Dempet',
'Gajah',
'Guntur',
'Karang Tengah',
'Karanganyar',
'Karangawen',
'Kebonagung',
'Mijen',
'Mranggen',
'Sayung',
'Wedung',
'Wonosalam',
'Brati',
'Gabus',
'Geyer',
'Godong',
'Grobogan',
'Gubug',
'Karangrayung',
'Kedungjati',
'Klambu',
'Kradenan',
'Ngaringan',
'Penawangan',
'Pulokulon',
'Tanggungharjo',
'Tawangharjo',
'Tegowanu',
'Toroh',
'Wirosari',
'Karimunjawa',
'Colomadu',
'Gondangrejo',
'Jaten',
'Jatipuro',
'Jatiyoso',
'Jenawi',
'Jumantono',
'Jumapolo',
'Karanganyar',
'Karangpandan',
'Kebakkramat',
'Kerjo',
'Matesih',
'Mojogedang',
'Ngargoyoso',
'Tasikmadu',
'Tawangmangu',
'Adimulyo',
'Alian/aliyan',
'Ambal',
'Ayah',
'Bonorowo',
'Buayan',
'Buluspesantren',
'Gombong',
'Karanganyar',
'Karanggayam',
'Karangsambung',
'Kebumen',
'Klirong',
'Kutowinangun',
'Kuwarasan',
'Mirit',
'Padureso',
'Pejagoan',
'Petanahan',
'Poncowarno',
'Prembun',
'Puring',
'Rowokele',
'Sadang',
'Sempor',
'Sruweng',
'Boja',
'Brangsong',
'Cepiring',
'Gemuh',
'Kaliwungu',
'Kaliwungu Selatan',
'Kangkung',
'Limbangan',
'Ngampel',
'Pagerruyung',
'Patean',
'Patebon',
'Pegandon',
'Plantungan',
'Ringinarum',
'Rowosari',
'Singorojo',
'Sukorejo',
'Weleri',
'Bayat',
'Cawas',
'Ceper',
'Delanggu',
'Gantiwarno',
'Jatinom',
'Jogonalan',
'Juwiring',
'Kalikotes',
'Karanganom',
'Karangdowo',
'Karangnongko',
'Kebonarum',
'Kemalang',
'Manisrenggo',
'Ngawen',
'Pedan',
'Polanharjo',
'Prambanan',
'Trucuk',
'Tulung',
'Wedi',
'Wonosari',
'Bae',
'Dawe',
'Gebog',
'Jati',
'Jekulo',
'Kaliwungu',
'Kudus Kota',
'Mejobo',
'Undaan',
'Grabag',
'Kajoran',
'Mungkid',
'Ngablak',
'Ngluwar',
'Windusari',
'Batangan',
'Cluwak',
'Dukuhseti',
'Gabus',
'Gembong',
'Gunungwungkal',
'Jaken',
'Jakenan',
'Juwana',
'Kayen',
'Margorejo',
'Margoyoso',
'Pucakwangi',
'Sukolilo',
'Tambakromo',
'Tayu',
'Tlogowungu',
'Trangkil',
'Wedarijaksa',
'Winong',
'Bojong',
'Buaran',
'Doro',
'Kandangserang',
'Karanganyar',
'Karangdadap',
'Kedungwuni',
'Kesesi',
'Lebakbarang',
'Paninggaran',
'Petungkriono/petungkriyono',
'Siwalan',
'Sragi',
'Talun',
'Tirto',
'Wiradesa',
'Wonokerto',
'Wonopringgo',
'Ampelgading',
'Bantarbolang',
'Belik',
'Bodeh',
'Comal',
'Moga',
'Petarukan',
'Pulosari',
'Randudongkal',
'Taman',
'Ulujami',
'Warungpring',
'Watukumpul',
'Bobotsari',
'Bojongsari',
'Bukateja',
'Kaligondang',
'Kalimanah',
'Karanganyar',
'Karangjambu',
'Karangmoncol',
'Karangreja',
'Kejobong',
'Kemangkon',
'Kertanegara',
'Kutasari',
'Mrebet',
'Padamara',
'Pengadegan',
'Rembang',
'Bagelen',
'Banyuurip',
'Bayan',
'Bener',
'Bruno',
'Butuh',
'Gebang',
'Grabag',
'Kaligesing',
'Kemiri',
'Kutoarjo',
'Loano',
'Ngombol',
'Pituruh',
'Purwodadi',
'Purworejo',
'Bulu',
'Gunem',
'Kaliori',
'Kragan',
'Lasem',
'Pamotan',
'Pancur',
'Rembang',
'Sale',
'Sarang',
'Sedan',
'Sluke',
'Sulang',
'Sumber',
'Ambarawa',
'Bancak',
'Bandungan',
'Banyubiru',
'Bawen',
'Bergas',
'Bringin',
'Getasan',
'Jambu',
'Kaliwungu',
'Pabelan',
'Pringapus',
'Sumowono',
'Suruh',
'Susukan',
'Tengaran',
'Tuntang',
'Gemolong',
'Gesi',
'Gondang',
'Jenar',
'Kalijambe',
'Karangmalang',
'Kedawung',
'Masaran',
'Miri',
'Mondokan',
'Ngrampal',
'Plupuh',
'Sambirejo',
'Sambung Macan',
'Sidoharjo',
'Sukodono',
'Sumberlawang',
'Tangen',
'Tanon',
'Baki',
'Bendosari',
'Bulu',
'Gatak',
'Grogol',
'Kartasura',
'Mojolaban',
'Nguter',
'Polokarto',
'Tawangsari',
'Weru',
'Adiwerna',
'Balapulang',
'Bojong',
'Bumijawa',
'Dukuhturi',
'Dukuhwaru',
'Jatinegara',
'Kedung Banteng',
'Kramat',
'Lebaksiu',
'Margasari',
'Pagerbarang',
'Pangkah',
'Slawi',
'Surodadi',
'Talang',
'Tarub',
'Warurejo',
'Bansari',
'Bejen',
'Bulu',
'Candiroto',
'Gemawang',
'Jumo',
'Kaloran',
'Kandangan',
'Kedu',
'Kledung',
'Kranggan',
'Ngadirejo',
'Parakan',
'Pringsurat',
'Selopampang',
'Temanggung',
'Tembarak',
'Tlogomulyo',
'Tretep',
'Wonoboyo',
'Baturetno',
'Batuwarno',
'Bulukerto',
'Eromoko',
'Girimarto',
'Giritontro',
'Giriwoyo',
'Jatipurno',
'Jatiroto',
'Jatisrono',
'Karangtengah',
'Kismantoro',
'Manyaran',
'Ngadirojo',
'Nguntoronadi',
'Paranggupito',
'Pracimantoro',
'Puhpelem',
'Purwantoro',
'Selogiri',
'Sidoharjo',
'Slogohimo',
'Tirtomoyo',
'Wuryantoro',
'Garung',
'Kalibawang',
'Kalikajar',
'Kaliwiro',
'Kejajar',
'Kepil',
'Kertek',
'Leksono',
'Mojotengah',
'Sapuran',
'Selomerto',
'Sukoharjo',
'Wadaslintang',
'Watumalang',
'Wonosobo',
'Magelang Selatan',
'Magelang Tengah',
'Magelang Utara',
'Pekalongan Barat',
'Pekalongan Selatan',
'Pekalongan Timur',
'Pekalongan Utara',
'Argomulyo',
'Sidomukti',
'Sidorejo',
'Tingkir',
'Banyumanik',
'Candisari',
'Gajah Mungkur',
'Gayamsari',
'Genuk',
'Gunungpati',
'Mijen',
'Ngaliyan',
'Pedurungan',
'Semarang Barat',
'Semarang Selatan',
'Semarang Tengah',
'Semarang Timur',
'Semarang Utara',
'Tembalang',
'Tugu',
'Banjarsari',
'Jebres',
'Laweyan',
'Pasar Kliwon',
'Serengan',
'Margadana',
'Tegal Barat',
'Tegal Selatan',
'Tegal Timur',
'Arosbaya',
'Blega',
'Burneh',
'Galis',
'Geger',
'Kamal',
'Klampis',
'Kokop',
'Konang',
'Kwanyar',
'Labang',
'Modung',
'Sepulu',
'Socah',
'Tanah Merah',
'Tanjungbumi',
'Tragah',
'Bangorejo',
'Cluring',
'Gambiran',
'Giri',
'Glagah',
'Glenmore',
'Kabat',
'Kalibaru',
'Kalipuro',
'Licin',
'Muncar',
'Pesanggaran',
'Purwoharjo',
'Rogojampi',
'Sempu',
'Siliragung',
'Singojuruh',
'Songgon',
'Srono',
'Tegaldlimo',
'Tegalsari',
'Wongsorejo',
'Bakung',
'Binangun',
'Doko',
'Gandusari',
'Garum',
'Kademangan',
'Kanigoro',
'Kesamben',
'Nglegok',
'Panggungrejo',
'Ponggok',
'Sanan Kulon',
'Selopuro',
'Selorejo',
'Srengat',
'Sutojayan',
'Talun',
'Udanawu',
'Wates',
'Wonodadi',
'Wonotirto',
'Balen',
'Baureno',
'Bubulan',
'Dander',
'Gondang',
'Kalitidu',
'Kanor',
'Kapas',
'Kasiman',
'Kedewan',
'Kedungadem',
'Kepoh Baru',
'Malo',
'Margomulyo',
'Ngambon',
'Ngasem',
'Ngraho',
'Padangan',
'Purwosari',
'Sekar',
'Sugihwaras',
'Sukosewu',
'Sumberrejo',
'Tambakrejo',
'Temayang',
'Trucuk',
'Binakal',
'Botolinggo',
'Cermee',
'Jambe Sari D.s.',
'Klabang',
'Pujer',
'Sukosari',
'Sumber Wringin',
'Taman Krocok',
'Wringin',
'Balong Panggang',
'Benjeng',
'Bungah',
'Cerme',
'Driyorejo',
'Duduk Sampeyan',
'Dukun',
'Gresik',
'Kebomas',
'Kedamean',
'Manyar',
'Menganti',
'Panceng',
'Sangkapura',
'Sidayu',
'Tambak',
'Ujung Pangkah',
'Wringin Anom',
'Ajung',
'Ambulu',
'Arjasa',
'Balung',
'Bangsalsari',
'Gumuk Mas',
'Jelbuk',
'Jenggawah',
'Jombang',
'Kalisat',
'Kencong',
'Ledokombo',
'Mayang',
'Mumbulsari',
'Pakusari',
'Panti',
'Puger',
'Rambipuji',
'Semboro',
'Silo',
'Sukorambi',
'Sukowono',
'Sumber Baru',
'Sumber Jambe',
'Tanggul',
'Tempurejo',
'Umbulsari',
'Wuluhan',
'Bandar Kedung Mulyo',
'Bareng',
'Diwek',
'Gudo',
'Jogoroto',
'Kabuh',
'Kesamben',
'Kudu',
'Megaluh',
'Mojoagung',
'Mojowarno',
'Ngoro',
'Ngusikan',
'Perak',
'Peterongan',
'Plandaan',
'Ploso',
'Sumobito',
'Tembelang',
'Wonosalam',
'Badas',
'Banyakan',
'Grogol',
'Kandangan',
'Kandat',
'Kayen Kidul',
'Kepung',
'Kras',
'Kunjang',
'Mojo',
'Ngancar',
'Ngasem',
'Pagu',
'Papar',
'Plemahan',
'Plosoklaten',
'Puncu',
'Purwoasri',
'Ringinrejo',
'Semen',
'Tarokan',
'Wates',
'Babat',
'Bluluk',
'Brondong',
'Deket',
'Glagah',
'Kalitengah',
'Karang Geneng',
'Karangbinangun',
'Kedungpring',
'Kembangbahu',
'Laren',
'Maduran',
'Mantup',
'Modo',
'Ngimbang',
'Paciran',
'Pucuk',
'Sambeng',
'Sarirejo',
'Sekaran',
'Solokuro',
'Sugio',
'Sukodadi',
'Sukorame',
'Tikung',
'Turi',
'Candipuro',
'Gucialit',
'Jatiroto',
'Kedungjajang',
'Klakah',
'Kunir',
'Padang',
'Pasirian',
'Pasrujambe/pasujambe',
'Pronojiwo',
'Randuagung',
'Ranuyoso',
'Rowokangkung',
'Senduro',
'Sumbersuko',
'Tekung',
'Tempeh',
'Tempursari',
'Yosowilangun',
'Balerejo',
'Dagangan',
'Dolopo',
'Geger',
'Gemarang',
'Kare',
'Kebonsari',
'Mejayan',
'Pilangkenceng',
'Saradan',
'Sawahan',
'Wonoasri',
'Wungu',
'Barat',
'Bendo',
'Karangrejo',
'Karas',
'Kartoharjo (Kertoharjo)',
'Kawedanan',
'Lembeyan',
'Maospati',
'Ngariboyo',
'Nguntoronadi',
'Panekan',
'Parang',
'Plaosan',
'Poncol',
'Sidorejo',
'Sukomoro',
'Takeran',
'Ampelgading',
'Bantur',
'Bululawang',
'Dampit',
'Dau',
'Donomulyo',
'Gedangan',
'Gondanglegi',
'Jabung',
'Kalipare',
'Karangploso',
'Kasembon',
'Kromengan',
'Lawang',
'Ngajum',
'Ngantang',
'Pagak',
'Pagelaran',
'Pakis',
'Pakisaji',
'Poncokusumo',
'Pujon',
'Singosari',
'Sumbermanjing Wetan',
'Sumberpucung',
'Tajinan',
'Tirtoyudo',
'Tumpang',
'Wagir',
'Wajak',
'Wonosari',
'Bangsal',
'Dawar Blandong',
'Dlanggu',
'Gedeg',
'Gondang',
'Jatirejo',
'Jetis',
'Kemlagi',
'Kutorejo',
'Mojoanyar',
'Mojosari',
'Ngoro',
'Pacet',
'Pungging',
'Puri',
'Sooko',
'Trawas',
'Trowulan',
'Bagor',
'Baron',
'Berbek',
'Gondang',
'Jatikalen',
'Kertosono',
'Lengkong',
'Loceret',
'Ngetos',
'Ngluyu',
'Ngronggot',
'Pace',
'Patianrowo',
'Prambon',
'Rejoso',
'Sawahan',
'Sukomoro',
'Tanjunganom',
'Wilangan',
'Bringin',
'Geneng',
'Gerih',
'Jogorogo',
'Karanganyar',
'Karangjati',
'Kasreman',
'Kedunggalar',
'Kendal',
'Kwadungan',
'Mantingan',
'Ngrambe',
'Padas',
'Pangkur',
'Paron',
'Pitu',
'Sine',
'Widodaren',
'Arjosari',
'Bandar',
'Donorojo',
'Kebon Agung',
'Nawangan',
'Ngadirojo',
'Pringkuku',
'Punung',
'Sudimoro',
'Tegalombo',
'Tulakan',
'Batumarmar',
'Galis',
'Kadur',
'Larangan',
'Pademawu',
'Pakong',
'Palenga\'an',
'Pasean',
'Pegantenan',
'Proppo',
'Tlanakan',
'Waru',
'Babadan',
'Badegan',
'Balong',
'Bungkal',
'Jambon',
'Jenangan',
'Jetis',
'Kauman',
'Mlarak',
'Ngebel',
'Ngrayun',
'Pudak',
'Pulung',
'Sambit',
'Sampung',
'Sawoo',
'Siman',
'Slahung',
'Sooko',
'Sukorejo',
'Bantaran',
'Banyu Anyar',
'Besuk',
'Gading',
'Gending',
'Kota Anyar',
'Krejengan',
'Krucil',
'Kuripan',
'Lumbang',
'Maron',
'Paiton',
'Pajarakan',
'Pakuniran',
'Sukapura',
'Sumber',
'Sumberasih',
'Tegal Siwalan',
'Tiris',
'Tongas',
'Wonomerto',
'Banyuates',
'Camplong',
'Jrengik',
'Karang Penang',
'Kedungdung',
'Ketapang',
'Omben',
'Pangarengan',
'Robatal',
'Sokobanah',
'Sreseh',
'Tambelangan',
'Torjun',
'Balongbendo',
'Buduran',
'Candi',
'Gedangan',
'Jabon',
'Krembung',
'Krian',
'Porong',
'Prambon',
'Sedati',
'Sidoarjo',
'Sukodono',
'Taman',
'Tanggulangin',
'Tarik',
'Tulangan',
'Waru',
'Wonoayu',
'Arjasa',
'Asembagus',
'Banyuglugur',
'Banyuputih',
'Besuki',
'Bungatan',
'Jangkar',
'Jatibanteng',
'Kapongan',
'Kendit',
'Mangaran',
'Mlandingan',
'Panarukan',
'Panji',
'Situbondo',
'Suboh',
'Sumbermalang',
'Arjasa',
'Gayam',
'Gili Ginting (Giligenteng)',
'Masalembu',
'Nonggunong',
'Ra\'as (Raas)',
'Sapeken',
'Talango',
'Bendungan',
'Dongko',
'Durenan',
'Gandusari',
'Kampak',
'Karangan',
'Munjungan',
'Panggul',
'Pogalan',
'Pule',
'Suruh',
'Tugu',
'Watulimo',
'Bancar',
'Bangilan',
'Grabagan',
'Jatirogo',
'Jenu',
'Kenduruan',
'Kerek',
'Merakurak',
'Montong',
'Palang',
'Parengan',
'Plumpang',
'Rengel',
'Semanding',
'Senori',
'Singgahan',
'Soko',
'Tambakboyo',
'Widang',
'Bandung',
'Besuki',
'Boyolangu',
'Campur Darat',
'Gondang',
'Kalidawir',
'Karang Rejo',
'Kauman',
'Kedungwaru',
'Ngantru',
'Ngunut',
'Pagerwojo',
'Pakel',
'Pucanglaban',
'Rejotangan',
'Sendang',
'Sumbergempol',
'Tanggung Gunung',
'Kediri Kota',
'Mojoroto',
'Pesantren',
'Kartoharjo',
'Manguharjo',
'Taman',
'Blimbing',
'Kedungkandang',
'Klojen',
'Lowokwaru',
'Sukun',
'Magersari',
'Prajurit Kulon',
'Asemrowo',
'Benowo',
'Bubutan',
'Bulak',
'Dukuh Pakis',
'Gayungan',
'Genteng',
'Gubeng',
'Gununganyar',
'Jambangan',
'Karangpilang',
'Kenjeran',
'Krembangan',
'Lakar Santri',
'Mulyorejo',
'Pabean Cantikan',
'Pakal',
'Rungkut',
'Sambikerep',
'Sawahan',
'Semampir',
'Simokerto',
'Sukolilo',
'Sukomanunggal',
'Tambaksari',
'Tandes',
'Tegalsari',
'Tenggilis Mejoyo',
'Wiyung',
'Wonocolo',
'Wonokromo',
'Capkala',
'Jagoi Babang',
'Ledo',
'Lembah Bawang',
'Lumar',
'Monterado',
'Samalantan',
'Sanggau Ledo',
'Seluas',
'Siding',
'Sungai Betung',
'Sungai Raya',
'Sungai Raya Kepulauan',
'Suti Semarang',
'Teriak',
'Tujuh Belas',
'Badau',
'Batang Lupar',
'Bika',
'Boyan Tanjung',
'Bunut Hilir',
'Bunut Hulu',
'Embaloh Hilir',
'Embaloh Hulu',
'Embau',
'Empanang',
'Hulu Gurung',
'Jongkong (Jengkong)',
'Kalis',
'Kedamin',
'Manday',
'Mentebah',
'Pengkadan (Batu Datu)',
'Puring Kencana',
'Putussibau Selatan',
'Putussibau Utara',
'Seberuang',
'Selimbau',
'Semitau',
'Silat Hilir',
'Silat Hulu',
'Suhaid',
'Pulau Maya Karimata',
'Seponti',
'Simpang Hilir',
'Sukadana',
'Teluk Batang',
'Air Upas',
'Benua Kayong',
'Hulu Sungai',
'Jelai Hulu',
'Kendawangan',
'Manis Mata',
'Marau',
'Matan Hilir Selatan',
'Matan Hilir Utara',
'Muara Pawan',
'Nanga Tayap',
'Pemahan',
'Sandai',
'Simpang Dua',
'Simpang Hulu',
'Singkup',
'Sungai Laur',
'Sungai Melayu Rayak',
'Tumbang Titi',
'Batu Ampar',
'Kuala Mandor Kab. Kubu Raya',
'Kubu',
'Rasau Jaya Kab. Kubu Raya',
'Sei/sungai Ambawang',
'Sei/sungai Kakap',
'Teluk/telok Pakedai',
'Terentang',
'Air Besar',
'Banyuke Hulu',
'Jelimpo',
'Kuala Behe',
'Mandor',
'Mempawah Hulu',
'Menjalin',
'Menyuke',
'Meranti',
'Sebangki',
'Sengah Temila',
'Sompak',
'Belimbing',
'Belimbing Hulu',
'Ella Hilir',
'Menukung',
'Pinoh Selatan',
'Pinoh Utara',
'Sayan',
'Sokan',
'Tanah Pinoh',
'Tanah Pinoh Barat',
'Anjongan',
'Mempawah Hilir',
'Mempawah Timur',
'Sadaniang',
'Segedong',
'Sei/sungai Kunyit',
'Sei/sungai Pinyuh',
'Siantan',
'Toho',
'Galing',
'Jawai',
'Jawai Selatan',
'Paloh',
'Sajad',
'Sajingan Besar',
'Salatiga',
'Sebawi',
'Sejangkung',
'Selakau',
'Selakau Timur',
'Semparuk',
'Subah',
'Tangaran',
'Tebas',
'Tekarang',
'Teluk Keramat',
'Balai',
'Beduwai',
'Bonti',
'Entikong',
'Jangkang',
'Kembayan',
'Meliau',
'Mukok',
'Noyan',
'Parindu',
'Sanggau Kapuas',
'Sekayam',
'Tayan Hilir',
'Tayan Hulu',
'Toba',
'Belitang',
'Belitang Hilir',
'Belitang Hulu',
'Nanga Mahap',
'Nanga Taman',
'Sekadau Hulu',
'Ambalau',
'Binjai Hulu',
'Dedai',
'Kayan Hilir',
'Kayan Hulu',
'Kelam Permai',
'Ketungau Hilir',
'Ketungau Hulu',
'Ketungau Tengah',
'Sepauk',
'Serawai (Nanga Serawai)',
'Sungai Tebelian',
'Tempunak',
'Pontianak Barat',
'Pontianak Kota',
'Pontianak Selatan',
'Pontianak Tenggara',
'Pontianak Timur',
'Pontianak Utara',
'Singkawang Barat',
'Singkawang Selatan',
'Singkawang Tengah',
'Singkawang Timur',
'Singkawang Utara',
'Awayan',
'Batu Mandi',
'Halong',
'Juai',
'Lampihong',
'Paringin',
'Paringin Selatan',
'Tebing Tinggi',
'Aluh Aluh',
'Aranio',
'Astambul',
'Beruntung Baru',
'Gambut',
'Karang Intan',
'Kertak Hanyar',
'Martapura Barat',
'Martapura Kota',
'Martapura Timur',
'Mataraman',
'Pengaron',
'Peramasan',
'Sambung Makmur',
'Sei/sungai Pinang',
'Sei/sungai Tabuk',
'Simpang Empat',
'Tatah Makmur',
'Telaga Bauntung',
'Alalak',
'Anjir Muara',
'Anjir Pasar',
'Bakumpai',
'Barambai',
'Belawang',
'Cerbon',
'Jejangkit',
'Kuripan',
'Mandastana',
'Mekar Sari',
'Rantau Badauh',
'Tabukan',
'Tabunganen',
'Tamban',
'Wanaraya',
'Angkinang',
'Daha Barat',
'Daha Selatan',
'Daha Utara',
'Kalumpang (Kelumpang)',
'Loksado',
'Padang Batung',
'Simpur',
'Sungai Raya',
'Telaga Langsat',
'Batang Alai Selatan',
'Batang Alai Timur',
'Batang Alai Utara',
'Batu Benawa',
'Hantakan',
'Haruyan',
'Labuan Amas Selatan',
'Labuan Amas Utara',
'Limpasu',
'Pandawan',
'Babirik',
'Banjang',
'Danau Panggang',
'Haur Gading',
'Paminggir',
'Sungai Pandan',
'Sungai Tabukan',
'Hampang',
'Kelumpang Barat',
'Kelumpang Hilir',
'Kelumpang Hulu',
'Kelumpang Selatan',
'Kelumpang Tengah',
'Kelumpang Utara',
'Pamukan Barat',
'Pamukan Selatan',
'Pamukan Utara',
'Pulau Laut Barat',
'Pulau Laut Kepulauan',
'Pulau Laut Selatan',
'Pulau Laut Tengah',
'Pulau Laut Timur',
'Pulau Laut Utara',
'Pulau Sebuku',
'Pulau Sembilan',
'Sampanahan',
'Sungai Durian',
'Banua Lawas',
'Bintang Ara',
'Haruai',
'Jaro',
'Kelua',
'Muara Harus',
'Muara Uya',
'Murung Pudak',
'Pugaan',
'Tanta',
'Upau',
'Angsana',
'Batulicin',
'Karang Bintang',
'Kuranji',
'Kusan Hilir',
'Kusan Hulu',
'Mantewe',
'Satui',
'Simpang Empat',
'Sungai Loban',
'Bati-Bati',
'Batu Ampar',
'Jorong',
'Kintap',
'Kurau',
'Panyipatan',
'Takisung',
'Tambang Ulang',
'Bakarangan',
'Binuang',
'Bungur',
'Candi Laras Selatan',
'Candi Laras Utara',
'Hatungun',
'Lokpaikat',
'Piani',
'Salam Babaris',
'Tapin Selatan',
'Tapin Tengah',
'Tapin Utara',
'Banjar Baru Selatan',
'Banjar Baru Utara',
'Cempaka',
'Landasan Ulin',
'Liang Anggang',
'Banjarmasin Barat',
'Banjarmasin Selatan',
'Banjarmasin Tengah',
'Banjarmasin Timur',
'Banjarmasin Utara',
'Dusun Hilir',
'Dusun Selatan',
'Dusun Utara',
'Gunung Bintang Awai',
'Jenamas',
'Karau Kuala',
'Awang',
'Benua Lima',
'Dusun Tengah',
'Dusun Timur',
'Paju Epat',
'Paku',
'Patangkep Tutui',
'Pematang Karau',
'Raren Batuah',
'Gunung Purei',
'Gunung Timang',
'Lahei',
'Montalat',
'Teweh Tengah',
'Teweh Timur',
'Kahayan Hulu Utara',
'Rungan',
'Tewah',
'Basarang',
'Kapuas Barat',
'Kapuas Hilir',
'Kapuas Hulu',
'Kapuas Kuala',
'Kapuas Murung',
'Kapuas Tengah',
'Kapuas Timur',
'Mantangai',
'Pulau Petak',
'Selat',
'Timpah',
'Kamipang',
'Katingan Hulu',
'Katingan Kuala',
'Marikit',
'Sanaman Mantikei (Senamang Mantikei)',
'Tasik Payawan',
'Tewang Sanggalang Garing (Sangalang)',
'Arut Utara',
'Kotawaringin Lama',
'Kumai',
'Pangkalan Banteng',
'Pangkalan Lada',
'Antang Kalang',
'Baamang',
'Bukit Santuei',
'Cempaga',
'Cempaga Hulu',
'Kota Besi',
'Mentawa Baru (Ketapang)',
'Mentaya Hilir Selatan',
'Mentaya Hilir Utara',
'Mentaya Hulu',
'Parenggean',
'Pulau Hanaut',
'Seranau',
'Telawang',
'Teluk Sampit',
'Delang',
'Barito Tuhup Raya',
'Laung Tuhup',
'Murung',
'Permata Intan',
'Seribu Riam',
'Sumber Barito',
'Sungai Babuat',
'Tanah Siang',
'Tanah Siang Selatan',
'Uut Murung',
'Kahayan Kuala',
'Maliku',
'Hanau',
'Seruyan Hulu',
'Seruyan Tengah',
'Balai Riam',
'Jelai',
'Pantai Lunci',
'Permata Kecubung',
'Bukit Batu',
'Jekan Raya',
'Pahandut',
'Rakumpit',
'Sebangau',
'Batu Putih',
'Biatan',
'Biduk-Biduk',
'Gunung Tabur',
'Kelay',
'Maratua',
'Pulau Derawan',
'Sambaliung',
'Segah',
'Tabalar',
'Talisayan',
'Teluk Bayur',
'Peso',
'Peso Hilir/ilir',
'Pulau Bunyu',
'Sekatak',
'Tanjung Palas',
'Tanjung Palas Barat',
'Tanjung Palas Tengah',
'Tanjung Palas Timur',
'Tanjung Palas Utara',
'Tanjung Selor',
'Bentian Besar',
'Bongan',
'Damai',
'Jempang',
'Long Apari',
'Long Bagun',
'Long Hubung',
'Long Iram',
'Long Pahangai',
'Kembang Janggut',
'Kenohan',
'Tabang',
'Batu Ampar',
'Busang',
'Karangan',
'Kaubun',
'Kongbeng',
'Long Mesangat (Mesengat)',
'Muara Ancalong',
'Muara Bengkal',
'Sandaran',
'Telen',
'Bahau Hulu',
'Kayan Hilir',
'Kayan Hulu',
'Kayan Selatan',
'Malinau Barat',
'Malinau Kota',
'Mentarang',
'Mentarang Hulu',
'Pujungan',
'Sungai Boh',
'Krayan',
'Krayan Selatan',
'Lumbis',
'Sebatik',
'Sebatik Barat',
'Sebuku',
'Sembakung',
'Batu Engau',
'Muara Samu',
'Pasir Belengkong',
'Tanjung Harapan',
'Babulu',
'Penajam',
'Sepaku',
'Waru',
'Sesayap',
'Sesayap Hilir',
'Tana Lia (Tanah Lia)',
'Balikpapan Barat',
'Balikpapan Selatan',
'Balikpapan Tengah',
'Balikpapan Timur',
'Balikpapan Utara',
'Bontang Barat',
'Bontang Selatan',
'Bontang Utara',
'Palaran',
'Samarinda Ilir',
'Samarinda Seberang',
'Samarinda Ulu',
'Samarinda Utara',
'Sungai Kunjang',
'Tarakan Barat',
'Tarakan Tengah',
'Tarakan Timur',
'Tarakan Utara',
'Bintan Pesisir',
'Bintan Timur',
'Bintan Utara',
'Gunung Kijang',
'Mantang',
'Seri/sri Kuala Lobam',
'Tambelan',
'Teluk Bintan',
'Teluk Sebong',
'Toapaya',
'Buru',
'Moro',
'Jemaja',
'Jemaja Timur',
'Palmatak',
'Siantan',
'Siantan Selatan',
'Siantan Tengah',
'Siantan Timur',
'Lingga Utara',
'Senayang',
'Singkep Barat',
'Bunguran Barat',
'Bunguran Tengah',
'Bunguran Timur',
'Bunguran Timur Laut',
'Bunguran Utara',
'Midai',
'Pulau Laut',
'Pulau Tiga',
'Serasan',
'Subi',
'Batam Kota',
'Batu Aji',
'Batu Ampar',
'Belakang Padang',
'Bengkong',
'Bulang',
'Galang',
'Lubuk Baja',
'Nongsa',
'Sagulung',
'Sei Beduk',
'Sekupang/ Tanjung Ucang',
'Suoh',
'Bakauheni',
'Candipuro',
'Jati Agung',
'Katibung',
'Ketapang',
'Merbau Mataram',
'Palas',
'Penengahan',
'Rajabasa',
'Sidomulyo',
'Sragi',
'Tanjung Bintang',
'Tanjung Sari',
'Way Panji',
'Way Sulan',
'Selagai Lingga',
'Bandar Sribawono',
'Batanghari',
'Batanghari Nuban',
'Braja Slebah',
'Bumi Agung',
'Gunung Pelindung',
'Jabung',
'Labuhan Maringgai',
'Labuhan Ratu',
'Marga Sekampung',
'Margatiga',
'Mataram Baru',
'Melinting',
'Metro Kibang',
'Pasir Sakti',
'Pekalongan',
'Purbolinggo',
'Raman Utara',
'Sekampung',
'Sekampung Udik',
'Sukadana',
'Waway Karya',
'Way Bungur (Purbolinggo Utara)',
'Abung Barat',
'Abung Kunang',
'Abung Pekurun',
'Abung Selatan',
'Abung Semuli',
'Abung Surakarta',
'Abung Tengah',
'Abung Timur',
'Abung Tinggi',
'Blambangan Pagar',
'Bukit Kemuning',
'Bunga Mayang',
'Hulu Sungkai',
'Kotabumi',
'Kotabumi Selatan',
'Kotabumi Utara',
'Muara Sungkai',
'Sungkai Barat',
'Sungkai Jaya',
'Sungkai Selatan',
'Sungkai Tengah',
'Sungkai Utara',
'Tanjung Raja',
'Mesuji',
'Mesuji Timur',
'Panca Jaya',
'Simpang Pematang',
'Tanjung Raya',
'Way Serdang',
'Gedong Tataan (Gedung Tataan)',
'Kedondong',
'Negeri Katon',
'Padang Cermin',
'Punduh Pidada (Pedada)',
'Tegineneng',
'Way Lima',
'Adi Luwih',
'Ambarawa',
'Banyumas',
'Gading Rejo',
'Pagelaran',
'Pardasuka',
'Pringsewu',
'Sukoharjo',
'Air Naningan',
'Bandar Negeri Semuong',
'Bulok',
'Cukuh Balak',
'Gisting',
'Gunung Alip',
'Kelumbayan',
'Kelumbayan Barat',
'Kota Agung Barat',
'Kota Agung Pusat',
'Kota Agung Timur',
'Limau',
'Pematang Sawa',
'Pugung',
'Pulau Panggung',
'Semaka',
'Sumberejo',
'Talang Padang',
'Ulubelu',
'Wonosobo',
'Rawajitu Selatan',
'Rawajitu Utara',
'Gunung Agung',
'Gunung Terang',
'Lambu Kibang',
'Pagar Dewa',
'Tulang Bawang Tengah',
'Tulang Bawang Udik',
'Tumijajar',
'Way Kenanga',
'Negeri Agung',
'Negeri Besar',
'Kedaton',
'Kemiling',
'Panjang',
'Rajabasa',
'Sukabumi',
'Sukarame',
'Tanjung Karang Barat',
'Tanjung Karang Pusat',
'Tanjung Karang Timur',
'Tanjung Senang',
'Telukbetung Barat',
'Telukbetung Selatan',
'Telukbetung Utara',
'Metro Barat',
'Metro Pusat',
'Metro Selatan',
'Metro Timur',
'Metro Utara',
'Air buaya',
'Wayapo / Buru Utara Timur',
'Ambalau',
'Kepala Madan',
'Leksula',
'Namrole',
'Waesama',
'Aru Selatan Barat',
'Aru Selatan Timur',
'Aru Tengah',
'Aru Tengah Selatan',
'Aru Tengah Timur',
'Aru Utara',
'Pulau-Pulau Aru',
'Damer',
'Mdona Hyera/hiera',
'Moa Lakor',
'Pulau Letti (Leti Moa Lakor)',
'Pulau Pulau Babar',
'Pulau Pulau Terselatan',
'Pulau-Pulau Babar Timur',
'Amahai',
'Banda',
'Leihitu',
'Leihitu Barat',
'Nusalaut',
'Pulau Haruku',
'Saparua',
'Seram Utara',
'Seram Utara Barat',
'Tehoru',
'Teluk Elpaputih',
'Teon Nila Serua',
'Kei Besar',
'Kei Besar Selatan',
'Kei Besar Utara Timur',
'Kei Kecil',
'Kei Kecil Barat',
'Kei Kecil Timur',
'Kormomolin',
'Nirunmas',
'Pulau-Pulau Wetar',
'Selaru',
'Tanimbar Selatan',
'Tanimbar Utara',
'Wermakatian (Wer Maktian)',
'Wertamrian',
'Wuarlabobar',
'Yaru',
'Kairatu',
'Seram Barat',
'Taniwel',
'Waisala',
'Bula',
'Pulau Gorong (Gorom)',
'Seram Timur',
'Tutuk Tolu',
'Werinama',
'Leitimur Selatan',
'Nusa niwe',
'Sirimau',
'Teluk Ambon',
'Teluk Ambon Baguala',
'Pulau Dullah Selatan',
'Pulau Dullah Utara',
'Pulau Tayando Tam',
'Pulau-Pulau Kur',
'Ibu',
'Loloda',
'Gane Barat',
'Gane Timur',
'Kayoa',
'Makian Barat (Pulau Makian)',
'Obi',
'Obi Selatan',
'Patani',
'Wasile',
'Wasile Selatan',
'Loloda Utara',
'Malifut',
'Sulabesi Barat',
'Taliabu Barat',
'Taliabu Timur',
'Morotai Jaya',
'Morotai Selatan',
'Morotai Selatan Barat',
'Morotai Timur',
'Morotai Utara',
'Moti (Pulau Moti)',
'Oba',
'Oba Selatan',
'Oba Tengah',
'Oba Utara',
'Tidore Selatan',
'Tidore Timur (Pulau Tidore)',
'Tidore Utara',
'Arongan Lambalek',
'Bubon',
'Johan Pahlawan',
'Kaway Xvi',
'Meureubo',
'Pante Ceureumen (Pantai Ceuremen)',
'Panton Reu',
'Samatiga',
'Sungai Mas',
'Woyla',
'Woyla Barat',
'Woyla Timur',
'Babah Rot',
'Jeumpa',
'Kuala Batee',
'Lembah Sabil',
'Manggeng',
'Setia',
'Susoh',
'Tangan-Tangan',
'Baitussalam',
'Blank Bintang',
'Darul Imarah',
'Darul Kamal',
'Darussalam',
'Indrapuri',
'Ingin Jaya',
'Kota Cot Glie (Kuta Cot Glie)',
'Kota Jantho',
'Kota Malaka (Kuta Malaka)',
'Krueng Barona Jaya',
'Kuta Baro',
'Lembah Seulawah',
'Leupung',
'Lhoknga (Lho\'nga)',
'Lhoong',
'Mantasiek (Montasik)',
'Mesjid Raya',
'Peukan Bada',
'Pulo Aceh',
'Seulimeum',
'Simpang Tiga',
'Suka Makmur',
'Jaya',
'Keude Panga',
'Krueng Sabee',
'Sampoiniet',
'Setia Bakti',
'Teunom',
'Bakongan',
'Bakongan Timur',
'Kluet Selatan',
'Kluet Tengah',
'Kluet Timur',
'Kluet Utara',
'Labuhan Haji',
'Labuhan Haji Barat',
'Labuhan Haji Timur',
'Meukek',
'Pasie Raja',
'Sama Dua',
'Sawang',
'Trumon',
'Trumon Timur',
'Danau Paris',
'Gunung Meriah (Mariah)',
'Kota Baharu',
'Kuala Baru',
'Pulau Banyak',
'Simpang Kanan',
'Singkil Utara',
'Singkohor',
'Suro Makmur',
'Banda Mulia',
'Bandar Pusaka',
'Bendahara',
'Karang Baru',
'Kejuruan Muda',
'Kota Kuala Simpang',
'Manyak Payed',
'Rantau',
'Sekerak',
'Seruway',
'Tamiang Hulu',
'Tenggulun',
'Atu Lintang',
'Bebesen',
'Bies',
'Bintang',
'Celala',
'Jagong Jeget',
'Kebayakan',
'Ketol',
'Kute Panang',
'Linge',
'Lut Tawar',
'Pegasing',
'Rusip Antara',
'Silih Nara',
'Babul Makmur',
'Babul Rahmah',
'Babussalam',
'Badar',
'Bambel',
'Bukit Tusam',
'Darul Hasanah',
'Deleng Pokhisen',
'Ketambe',
'Lawe Alas',
'Lawe Bulan',
'Lawe Sigala-Gala',
'Lawe Sumur',
'Leuser',
'Semadam',
'Tanah Alas',
'Banda Alam',
'Birem Bayeun',
'Darul Aman',
'Darul Falah',
'Darul Iksan (Ihsan)',
'Idi Timur',
'Idi Tunong',
'Indra Makmur',
'Julok',
'Madat',
'Nurussalam',
'Pante Bidari (Beudari)',
'Peudawa',
'Peunaron',
'Peureulak',
'Peureulak Barat',
'Peureulak Timur',
'Rantau Selamat',
'Ranto Peureulak',
'Serba Jadi',
'Simpang Jernih',
'Simpang Ulim',
'Sungai Raya',
'Baktiya',
'Baktiya Barat',
'Banda Baro',
'Cot Girek',
'Dewantara',
'Geuredong Pase',
'Kuta Makmur',
'Langkahan',
'Lapang',
'Matangkuli',
'Meurah Mulia',
'Muara Batu',
'Nibong',
'Nisam',
'Nisam Antara',
'Paya Bakong',
'Pirak Timur',
'Samudera',
'Sawang',
'Seunuddon (Seunudon)',
'Simpang Kramat (Keramat)',
'Syamtalira Aron',
'Syamtalira Bayu',
'Tanah Jambo Aye',
'Tanah Luas',
'Tanah Pasir',
'Bandar',
'Bukit',
'Permata',
'Pintu Rime Gayo',
'Syiah Utama',
'Timang Gajah',
'Wih Pesam',
'Ganda Pura',
'Jangka',
'Jeumpa',
'Jeunieb',
'Juli',
'Kota Juang',
'Kuala',
'Kuta Blang',
'Makmur',
'Pandrah',
'Peudada',
'Peulimbang (Plimbang)',
'Peusangan',
'Peusangan Selatan',
'Peusangan Siblah Krueng',
'Samalanga',
'Simpang Mamplam',
'Blang Jerango',
'Blang Kejeren',
'Blang Pegayon',
'Dabun Gelang (Debun Gelang)',
'Kuta Panjang',
'Pantan Cuaca',
'Pining (Pinding)',
'Putri Betung',
'Rikit Gaib',
'Terangun (Terangon)',
'Teripe/tripe Jaya',
'Beutong',
'Darul Makmur',
'Kuala',
'Kuala Pesisir',
'Seunagan',
'Seunagan Timur',
'Suka Makmue',
'Tadu Raya',
'Batee',
'Delima',
'Geumpang',
'Glumpang Baro',
'Glumpang Tiga (Geulumpang Tiga)',
'Grong Grong',
'Indrajaya',
'Kembang Tanjong (Tanjung)',
'Keumala',
'Kota Sigli',
'Mane',
'Mila',
'Muara Tiga',
'Mutiara',
'Mutiara Timur',
'Padang Tiji',
'Peukan Baro',
'Pidie',
'Sakti',
'Simpang Tiga',
'Tangse',
'Tiro/truseb',
'Titeue',
'Bandar Baru',
'Bandar Dua',
'Jangka Buya',
'Meurah Dua',
'Panteraja',
'Trienggadeng',
'Ulim',
'Alapan (Alafan)',
'Salang',
'Simeuleu Barat',
'Simeuleu Tengah',
'Simeuleu Timur',
'Teluk Dalam Simeuleu',
'Teupah Barat',
'Teupah Selatan',
'Baiturrahman',
'Banda Raya',
'Jaya Baru',
'Kuta Alam',
'Kuta Raja',
'Lueng Bata',
'Meuraxa',
'Syiah Kuala',
'Ulee Kareng',
'Langsa Barat',
'Langsa Baro',
'Langsa Kota',
'Langsa Lama',
'Langsa Timur',
'Banda Sakti',
'Blang Mangat',
'Muara Dua',
'Muara Satu',
'Sukajaya',
'Sukakarya',
'Longkib',
'Penanggalan',
'Rundeng',
'Simpang Kiri',
'Sultan Daulat',
'Ambalawi',
'Langgudu',
'Sanggar',
'Tambora',
'Hu\'u',
'Kempo',
'Kilo',
'Pajo',
'Pekat',
'Batu Layar',
'Gerung',
'Gunung sari',
'Kediri',
'Kuripan',
'Labu Api',
'Lembar',
'Lingsar',
'Narmada',
'Sekotong',
'Batukliang',
'Batukliang Utara',
'Janapria',
'Jonggat',
'Kopang',
'Praya',
'Praya Barat',
'Praya Barat Daya',
'Praya Tengah',
'Praya Timur',
'Pringgarata',
'Pujut',
'Aikmel',
'Jerowaru',
'Keruak',
'Labuhan Haji',
'Mas bagik',
'Montong Gading',
'Pringgabaya',
'Pringgasela',
'Sakra',
'Sakra Barat',
'Sakra Timur',
'Sambelia',
'Selong',
'Sembalun',
'Sikur',
'Suela',
'Sukamulia',
'Suralaga',
'Terara',
'Wanasaba',
'Bayan',
'Gangga',
'Kayangan',
'Pemenang',
'Tanjung',
'Batu lanteh',
'Labangka',
'Lunyuk',
'Ropang',
'Seteluk',
'Asakota',
'Mpunda',
'Raba',
'Rasanae Barat',
'Rasanae Timur',
'Ampenan',
'Cakranegara',
'Mataram',
'Sandubaya (Sandujaya)',
'Sekarbela',
'Selaparang (Selaprang)',
'Alor Barat Daya',
'Alor Barat Laut',
'Alor Selatan',
'Alor Tengah Utara',
'Alor Timur',
'Alor Timur Laut',
'Kabola',
'Lembur',
'Mataru',
'Pantar',
'Pantar Barat',
'Pantar Barat Laut',
'Pantar Tengah',
'Pantar Timur',
'Pulau Pura',
'Pureman',
'Kakuluk Mesak',
'Kobalima',
'Malaka Barat',
'Malaka Timur',
'Raihat',
'Rinhat',
'Sasitamean',
'Tasifeto Timur',
'Pulau Ende',
'Wewaria',
'Wolojita',
'Adonara Barat',
'Adonara Timur',
'Solor Barat',
'Solor Timur',
'Amabi Oefeto',
'Amabi Oefeto Timur',
'Amarasi',
'Amarasi Barat',
'Amarasi Selatan',
'Amarasi Timur',
'Amfoang Barat Daya',
'Amfoang Barat Laut',
'Amfoang Selatan',
'Amfoang Timur',
'Amfoang Utara',
'Fatuleu',
'Fatuleu Barat',
'Fatuleu Tengah',
'Nekemese',
'Semau',
'Semau Selatan',
'Sulamu',
'Taebenu',
'Takari',
'Atadei',
'Buyasuri (Buyasari)',
'Ile Ape',
'Ile Ape Timur',
'Lebatukan',
'Nagawutung',
'Nubatukan',
'Omesuri',
'Wulandoni (Wulandioni)',
'Cibal',
'Langke Rembong',
'Lelak',
'Rahong Utara',
'Reok',
'Satar Mese',
'Satar Mese Barat',
'Wae Rii',
'Boleng',
'Komodo',
'Kuwus',
'Lembor',
'Macang Pacar',
'Sano Nggoang',
'Welak',
'Borong',
'Elar',
'Kota Komba',
'Lamba Leda',
'Poco Ranaka',
'Sambi Rampas',
'Aesesa',
'Aesesa Selatan',
'Boawae',
'Keo Tengah',
'Mauponggo',
'Nangaroro',
'Wolowae',
'Aimere',
'Golewa',
'Riung',
'Soa',
'Lobalain',
'Pantai Baru',
'Rote Barat',
'Rote Barat Daya',
'Rote Barat Laut',
'Rote Selatan',
'Rote Tengah',
'Rote Timur',
'Hawu Mehara',
'Raijua',
'Sabu Barat',
'Sabu Liae',
'Sabu Tengah',
'Sabu Timur',
'Alok Barat',
'Alok Timur',
'Bola',
'Doreng',
'Hewokloang',
'Kangae',
'Kewapante',
'Koting',
'Lela',
'Magepanda',
'Mapitara',
'Mego',
'Nelle (Maumerei)',
'Nita',
'Paga',
'Palue',
'Talibura',
'Tana Wawo',
'Waiblama',
'Waigete',
'Kodi',
'Kodi Bangedo',
'Kodi Utara',
'Laura (Loura)',
'Wewewa Barat',
'Wewewa Selatan',
'Wewewa Timur',
'Wewewa Utara',
'Katikutana',
'Katikutana Selatan',
'Mamboro',
'Umbu Ratu Nggay',
'Umbu Ratu Nggay Barat',
'Haharu',
'Kahaunguweti (Kahaungu Eti)',
'Kambata Mapambuhang',
'Kambera',
'Karera',
'Katala Hamu Lingu',
'Lewa',
'Lewa Tidahu',
'Mahu',
'Matawai Lappau (La Pawu)',
'Ngadu Ngala',
'Nggaha Oriangu',
'Paberiwai',
'Pahunga Lodu',
'Pandawai',
'Pinupahar (Pirapahar)',
'Rindi',
'Tabundung',
'Umalulu',
'Wula Waijelu',
'Amanatun Selatan',
'Amanatun Utara',
'Amanuban Barat',
'Amanuban Selatan',
'Amanuban Tengah',
'Amanuban Timur',
'Batu Putih',
'Boking',
'Fatukopa',
'Fatumnasi',
'Fautmolo',
'Kie (Ki\'e)',
'Kok Baun',
'Kolbano',
'Kot Olin',
'Kualin',
'Kuanfatu',
'Kuatnana',
'Mollo Barat',
'Mollo Selatan',
'Mollo Tengah',
'Mollo Utara',
'Noebana',
'Noebeba',
'Nunbena',
'Nunkolo',
'Oenino',
'Polen',
'Santian',
'Tobu',
'Toianas',
'Biboki Anleu',
'Biboki Feotleu',
'Biboki Moenleu',
'Biboki Selatan',
'Biboki Tan Pah',
'Biboki Utara',
'Bikomi Nilulat',
'Bikomi Selatan',
'Bikomi Tengah',
'Bikomi Utara',
'Insana',
'Insana Barat',
'Insana Fafinesu',
'Insana Tengah',
'Insana Utara',
'Miomaffo Barat',
'Miomaffo Tengah',
'Miomaffo Timur',
'Musi',
'Mutis',
'Naibenu',
'Noemuti',
'Noemuti Timur',
'Alak',
'Kelapa Lima',
'Maulafa',
'Oebobo',
'Agats',
'Akat',
'Atsy',
'Fayit',
'Pantai Kasuari',
'Sawa Erma',
'Suator',
'Aimando Padaido',
'Andey (Andei)',
'Biak Barat',
'Biak Timur',
'Biak Utara',
'Bondifuar',
'Bruyadori',
'Numfor Barat',
'Numfor Timur',
'Oridek',
'Orkeri',
'Padaido',
'Poiru',
'Samofa',
'Swandiwe',
'Warsa',
'Yawosi',
'Yendidori',
'Ambatkwi (Ambatkui)',
'Arimop',
'Bomakia',
'Firiwage',
'Fofi',
'Iniyandit',
'Jair',
'Kombut',
'Kouh',
'Mandobo',
'Manggelum',
'Mindiptana',
'Subur',
'Waropko',
'Yaniruma',
'Bowobado',
'Kapiraya',
'Tigi',
'Tigi Barat',
'Tigi Timur',
'Kemtuk',
'Nimbokrang',
'Sentani Barat',
'Sentani Timur',
'Unurum Guay',
'Asologaima (Asalogaima)',
'Asolokobal',
'Bolakme',
'Hubikosi (Hobikosi)',
'Kurulu',
'Musatfak',
'Pelebaga',
'Poga',
'Walelagama',
'Wollo (Wolo)',
'Yalengga',
'Arso Timur',
'Senggi',
'Skamto (Skanto)',
'Towe (Towe Hitam)',
'Waris',
'Web',
'Angkaisera',
'Kepulauan Ambai',
'Kosiwo',
'Poom',
'Raimbawi',
'Teluk Ampimoi',
'Windesi',
'Wonawa',
'Yapen Barat',
'Yapen Selatan',
'Yapen Timur',
'Yapen Utara',
'Balingga',
'Dimba',
'Gamelia',
'Kuyawage',
'Makki (Maki)',
'Malagaineri (Malagineri)',
'Pirime',
'Tiom',
'Tiomneri',
'Benuki',
'Mamberamo Hilir/ilir',
'Mamberamo Hulu/ulu',
'Mamberamo Tengah',
'Mamberamo Tengah Timur',
'Rofaer (Rufaer)',
'Sawai',
'Waropen Atas',
'Eragayam',
'Ilugwa',
'Kelila',
'Kobakma',
'Megabilis (Megambilis)',
'Animha',
'Eligobel',
'Ilyawab',
'Jagebob',
'Kaptel',
'Kimaam',
'Kurik',
'Malind',
'Muting',
'Naukenjerai',
'Ngguti (Nggunti)',
'Okaba',
'Semangga',
'Sota',
'Tabonji',
'Tanah Miring',
'Tubang',
'Ulilin',
'Waan',
'Agimuga',
'Jila',
'Jita',
'Kuala Kencana',
'Mimika Barat',
'Mimika Barat Jauh',
'Mimika Barat Tengah',
'Mimika Baru',
'Mimika Timur',
'Mimika Timur Jauh',
'Mimika Timur Tengah',
'Tembagapura',
'Gearek',
'Geselma (Geselema)',
'Kenyam',
'Mapenduma',
'Mbua (Mbuga)',
'Mugi',
'Wosak',
'Yigi',
'Aboy',
'Batom',
'Bime',
'Borme',
'Iwur (Okiwur)',
'Kiwirok',
'Kiwirok Timur',
'Okbibab',
'Pepera',
'Agadugume',
'Beoga',
'Doufu',
'Gome',
'Ilaga',
'Pogoma',
'Sinak',
'Wangbe',
'Apawer Hulu',
'Bonggo',
'Bonggo Timur',
'Pantai Barat',
'Pantai Timur',
'Pantai Timur Barat',
'Sarmi Selatan',
'Sarmi Timur',
'Tor Atas',
'Kepulauan Aruri',
'Supiori Barat',
'Supiori Selatan',
'Supiori Timur',
'Supiori Utara',
'Airgaram',
'Bewani',
'Bokondini',
'Bokoneri',
'Dorman',
'Dow',
'Dundu (Ndundu)',
'Egiam',
'Geya',
'Gilubandu (Gilumbandu/gilimbandu)',
'Goyage',
'Gundagi (Gudage)',
'Kamboneri',
'Kanggime (Kanggima )',
'Kembu',
'Kondaga (Konda)',
'Kuari',
'Kubu',
'Nabunage',
'Nelawi',
'Numba',
'Nunggawi (Munggawi)',
'Panaga',
'Poganeri',
'Sbey',
'Tagineri',
'Timori',
'Umagi',
'Wari (Taiyeve)',
'Wina',
'Wonoki (Woniki)',
'Wunin (Wumin)',
'Yuneri',
'Inggerus',
'Kirihi',
'Masirei',
'Risei Sayati',
'Ureifasei',
'Waropen Bawah',
'Amuma',
'Anggruk',
'Bomela',
'Dekai',
'Dirwemna (Diruwena)',
'Duram',
'Endomen',
'Hereapini (Hereanini)',
'Hilipuk',
'Hogio (Hugio)',
'Holuon',
'Kabianggama (Kabianggema)',
'Kayo',
'Kona',
'Koropun (Korupun)',
'Kosarek',
'Kurima',
'Kwelemdua (Kwelamdua)',
'Kwikma',
'Langda',
'Lolat',
'Mugi',
'Musaik',
'Nalca',
'Ninia',
'Nipsan',
'Obio',
'Panggema',
'Pasema',
'Pronggoli (Proggoli)',
'Puldama',
'Samenage',
'Sela',
'Seredela (Seredala)',
'Silimo',
'Soba',
'Sobaham',
'Soloikma',
'Sumo',
'Suntamon',
'Suru Suru',
'Talambo',
'Tangma',
'Ubahak',
'Ubalihi',
'Ukha',
'Walma',
'Werima',
'Wusuma',
'Yahuliambut',
'Yogosem',
'Abenaho',
'Apalapsili',
'Benawa',
'Elelim',
'Welarek',
'Abepura',
'Heram',
'Jayapura Selatan',
'Jayapura Utara',
'Muara Tami',
'Bombarai (Bomberay)',
'Fakfak',
'Fakfak Barat',
'Fakfak Tengah',
'Fakfak Timur',
'Karas',
'Kokas',
'Kramongmongga (Kramamongga)',
'Teluk Patipi',
'Buruway',
'Kambraw (Kamberau)',
'Teluk Arguni Atas',
'Teluk Etna',
'Yamor',
'Yerusi (Teluk Arguni Bawah)',
'Anggi',
'Anggi Gida',
'Catubouw',
'Dataran Isim',
'Didohu',
'Hingk',
'Manokwari Barat',
'Manokwari Selatan',
'Manokwari Timur',
'Manokwari Utara',
'Masni',
'Membey',
'Menyambouw (Minyambouw)',
'Momi Waren',
'Neney (Nenei)',
'Oransbari',
'Prafi',
'Ransiki',
'Sidey',
'Sururey',
'Tahota (Tohota)',
'Taige',
'Tanah Rubuh',
'Testega',
'Warmare',
'Aifat',
'Aifat Timur',
'Aitinyo',
'Ayamaru',
'Ayamaru Utara',
'Mare',
'Kepulauan Ayau',
'Kofiau',
'Meos Mansar',
'Misool Barat',
'Misool Selatan',
'Misool Timur',
'Misool Utara',
'Salawati Utara (Samate)',
'Selat Sagawin',
'Teluk Mayalibit',
'Waigeo Barat',
'Waigeo Barat Kepulauan',
'Waigeo Selatan',
'Waigeo Timur',
'Waigeo Utara',
'Warwabomi',
'Aimas',
'Beraur',
'Klamono',
'Makbon',
'Mayamuk',
'Salawati',
'Salawati Selatan',
'Sayosa',
'Seget',
'Segun',
'Inanwatan',
'Kais (Matemani Kais)',
'Kokoda',
'Moswaren',
'Sawiat',
'Seremuk',
'Teminabuan',
'Wayer',
'Abun',
'Amberbaken',
'Fef (Peef)',
'Kebar',
'Miyah (Meyah)',
'Moraid',
'Mubrani',
'Sausapor',
'Senopi',
'Yembun',
'Aranday',
'Aroba',
'Babo',
'Bintuni',
'Biscoop',
'Dataran Beimes',
'Fafurwar (Irorutu)',
'Kaitaro',
'Kamundan',
'Kuri',
'Manimeri',
'Masyeta',
'Mayado',
'Merdey',
'Moskona Barat',
'Moskona Selatan',
'Moskona Timur',
'Moskona Utara',
'Sumuri (Simuri)',
'Tembuni',
'Tomu',
'Tuhiba',
'Wamesa (Idoor)',
'Weriagar',
'Rumberpon',
'Wamesa (Idoor)',
'Wasior',
'Wasior Barat',
'Wasior Selatan',
'Wasior Utara',
'Windesi',
'Sorong',
'Sorong Barat',
'Sorong Kepulauan',
'Sorong Timur',
'Sorong Utara',
'Rupat',
'Rupat Utara',
'Batang Tuaka',
'Concong',
'Enok',
'Gaung',
'Gaung Anak Serka',
'Kateman',
'Kempas',
'Kemuning',
'Keritang',
'Kuala Indragiri',
'Mandah',
'Pelangiran',
'Reteh',
'Sungai Batang',
'Tanah Merah',
'Teluk Belengkong',
'Tempuling',
'Batang Cenaku',
'Batang Gansal',
'Batang Peranap',
'Kelayang',
'Kuala Cenaku',
'Lirik',
'Lubuk Batu Jaya',
'Pasir Penyu',
'Peranap',
'Rakit Kulim',
'Rengat Barat',
'Seberida',
'Sungai Lala',
'Xiii Koto Kampar',
'Merbau',
'Rangsang',
'Rangsang Barat',
'Tebing Tinggi',
'Tebing Tinggi Barat',
'Benai',
'Cerenti',
'Gunung Toar',
'Hulu Kuantan',
'Inuman',
'Kuantan Hilir',
'Kuantan Mudik',
'Kuantan Tengah',
'Logas Tanah Darat',
'Pangean',
'Singingi',
'Singingi Hilir',
'Bandar Petalangan',
'Bandar Sei Kijang',
'Bunut',
'Kerumutan',
'Kuala Kampar',
'Langgam',
'Pangkalan Kerinci',
'Pangkalan Kuras',
'Pangkalan Lesung',
'Pelalawan',
'Teluk Meranti',
'Ukui',
'Kubu',
'Pasir Limau Kapas',
'Pujud',
'Rantau Kopar',
'Rimba Melintang',
'Simpang Kanan',
'Sinaboi',
'Kunto Darussalam',
'Bunga Raya',
'Dayun',
'Kandis',
'Kerinci Kanan',
'Koto Gasib',
'Lubuk Dalam',
'Mempura',
'Pusako',
'Sabak Auh',
'Siak',
'Sungai Apit',
'Sungai Mandau',
'Tualang',
'Bukit Kapur',
'Dumai Barat',
'Dumai Timur',
'Medang Kampai',
'Sungai Sembilan',
'Rumbai',
'Banggae',
'Banggae Timur',
'Malunda',
'Pamboang',
'Sendana',
'Tammeredo Sendana',
'Tubo (Tubo Sendana)',
'Ulumunda',
'Aralle',
'Balla',
'Bambang',
'Mambi',
'Messawa',
'Nosu',
'Pana',
'Rantebulahan Timur',
'Sesena Padang',
'Sumarorong',
'Tabang',
'Tabulahan',
'Tanduk Kalua',
'Tawalian',
'Bonehau',
'Budong-Budong',
'Kalukku',
'Kalumpang',
'Karossa',
'Pangale',
'Papalang',
'Sampaga',
'Simboro Dan Kepulauan',
'Tapalang Barat',
'Tappalang',
'Tobadak',
'Tommo',
'Topoyo',
'Bambaira',
'Bambalamotu',
'Baras',
'Bulu Taba',
'Dapurang',
'Duripoku',
'Pedongga',
'Sarjo',
'Sarudu',
'Tikke Raya',
'Allu',
'Anreapi',
'Balanipa',
'Binuang',
'Bulo',
'Campalagian',
'Limboro',
'Luyo',
'Mapilli',
'Matakali',
'Matangnga',
'Tapango',
'Tinambung',
'Tubbi Taramanu (Tutallu)',
'Wonomulyo',
'Bissappu',
'Eremerasa',
'Gantarang Keke (Gantareng Keke)',
'Pajukukang',
'Sinoa',
'Tompobulu',
'Uluere',
'Balusu',
'Mallusetasi',
'Pujananting',
'Soppeng Riaja',
'Tanete Riaja',
'Tanete Rilau',
'Ajangale',
'Amali',
'Awangpone',
'Barebbo',
'Bengo',
'Bontocani',
'Cenrana',
'Cina',
'Dua Boccoe',
'Kahu',
'Kajuara',
'Lamuru',
'Lappariaja',
'Libureng',
'Mare',
'Palakka',
'Patimpeng',
'Ponre',
'Salomekko',
'Sibulue',
'Tanete Riattang',
'Tanete Riattang Barat',
'Tanete Riattang Timur',
'Tellu Limpoe',
'Tellu Siattinge',
'Tonra',
'Ulaweng',
'Bonto Bahari',
'Bontotiro',
'Gantarang /Gantarangkindang/Ganking',
'Hero Lange-Lange (Herlang)',
'Kajang',
'Kindang',
'Rilau Ale',
'Ujung Bulu',
'Ujung Loe',
'Alla',
'Anggeraja',
'Baraka',
'Baroko',
'Bungin',
'Buntu Batu',
'Cendana',
'Curio',
'Maiwa',
'Malua',
'Masalle',
'Bajeng',
'Bajeng Barat',
'Barombong',
'Biringbulu',
'Bontolempangang',
'Bontomarannu',
'Bontonompo',
'Bontonompo Selatan',
'Bungaya',
'Manuju',
'Parangloe',
'Parigi',
'Pattallassang',
'Tinggimoncong',
'Tombolo Pao',
'Tompobulu',
'Arungkeke',
'Bangkala',
'Bangkala Barat',
'Batang',
'Binamu',
'Bontoramba',
'Kelara',
'Rumbia',
'Tamalatea',
'Tarowang',
'Turatea',
'Bajo',
'Bajo Barat',
'Bassesangtempe',
'Belopa',
'Belopa Utara',
'Bua',
'Bua Ponrang',
'Kamanre',
'Lamasi',
'Lamasi Timur',
'Larompong',
'Larompong Selatan',
'Latimojong',
'Ponrang',
'Ponrang Selatan',
'Suli',
'Suli Barat',
'Walenrang',
'Walenrang Barat',
'Walenrang Timur',
'Walenrang Utara',
'Angkona',
'Burau',
'Kalaena',
'Mangkutana',
'Nuha',
'Tomoni',
'Tomoni Timur',
'Towuti',
'Wasuponda',
'Wotu',
'Baebunta',
'Bone-Bone',
'Limbong',
'Malangke',
'Malangke Barat',
'Mappedeceng',
'Rampi',
'Sabbang',
'Seko',
'Sukamaju',
'Bantimurung',
'Camba',
'Cenrana',
'Lau',
'Mallawa',
'Mandai',
'Maros Baru',
'Maros Utara',
'Marusu',
'Moncongloe',
'Simbang',
'Tanralili',
'Tompu Bulu',
'Turikale',
'Balocci',
'Bungoro',
'Kalukuang Masalima',
'Labakkang',
'Liukang Tangaya',
'Liukang Tupabiring',
'Ma Rang',
'Mandalle',
'Minasa Tene',
'Segeri',
'Tondong Talasa',
'Batulappa',
'Cempa',
'Duampanua',
'Lanrisang',
'Lembang',
'Mattiro Bulu',
'Mattiro Sompe',
'Paleteang',
'Patampanua',
'Suppa',
'Tiroang',
'Watang Sawitto',
'Benteng',
'Bontoharu',
'Bontomanai',
'Bontomatene',
'Bontosikuyu',
'Buki',
'Pasilambena',
'Pasimarannu',
'Pasimasunggu',
'Pasimasunggu Timur',
'Takabonerate',
'Baranti',
'Dua Pitue',
'Kulo',
'Maritengngae',
'Panca Lautang',
'Panca Rijang',
'Pitu riase',
'Pitu Riawa',
'Sidenreng',
'Tellulimpo E',
'Watang Pulu',
'Bulupoddo',
'Pulau Sembilan',
'Sinjai Barat',
'Sinjai Borong',
'Sinjai Selatan',
'Sinjai Tengah',
'Sinjai Timur',
'Sinjai Utara',
'Tellu Limpoe',
'Citta',
'Donri Donri',
'Ganra',
'Lalabata',
'Lili Rilau',
'Liliraja (Lili Riaja)',
'Mario Riawa',
'Mario Riwawo',
'Galesong',
'Galesong Selatan',
'Galesong Utara',
'Mangara Bombang',
'Mappakasunggu',
'Patallassang',
'Polobangkeng Selatan',
'Polobangkeng Utara',
'Sanrobone',
'Bituang',
'Bonggakaradeng',
'Gandang Batu Silang',
'Kurra',
'Makale Selatan',
'Makale Utara',
'Malimbong Balepe',
'Mappak',
'Masanda',
'Mengkendek',
'Rano',
'Rembon',
'Saluputti',
'Sangalla',
'Sangalla Selatan',
'Sangalla Utara',
'Simbuang',
'Awan Rante Karua',
'Bangkelekila',
'Baruppu',
'Buntao Rantebua',
'Buntu Pepasan',
'Denpina/Dende Piongan Napo',
'Kapala Pitu',
'Kesu',
'Nanggala',
'Rantebua',
'Rantepao',
'Rantetayo',
'Rindingalo',
'Sa\'dan',
'Sa\'dan Balusu',
'Sanggalangi',
'Sesean',
'Sesean Suloara',
'Sopai',
'Tallunglipu',
'Tikala',
'Tondon Nanggala',
'Belawa',
'Bola',
'Gilireng',
'Keera',
'Majauleng',
'Maniang Pajo',
'Pammana',
'Penrang',
'Pitumpanua',
'Sabbang Paru',
'Sajoanging',
'Takkalalla',
'Tana Sitolo',
'Tempe',
'Biring Kanaya',
'Bontoala',
'Makassar',
'Mamajang',
'Manggala',
'Mariso',
'Panakkukang',
'Rappocini',
'Tallo',
'Tamalanrea',
'Tamalate',
'Ujung Pandang',
'Ujung Tanah',
'Wajo',
'Bara',
'Mungkajang',
'Sendana',
'Telluwanua',
'Wara',
'Wara Barat',
'Wara Selatan',
'Wara Timur',
'Wara Utara',
'Bacukiki',
'Bacukiki Barat',
'Soreang',
'Ujung',
'Balantak',
'Batui',
'Bualemo (Boalemo)',
'Bunta',
'Kintom',
'Lamala',
'Luwuk Timur',
'Masama',
'Nuhon',
'Pagimana',
'Toili',
'Toili Barat',
'Banggai Selatan',
'Banggai Tengah',
'Banggai Utara',
'Bangkurung',
'Bokan Kepulauan',
'Buko',
'Buko Selatan',
'Bulagi',
'Bulagi Selatan',
'Bulagi Utara',
'Labobo (Lobangkurung)',
'Liang',
'Peling Tengah',
'Tinangkung',
'Tinangkung Selatan',
'Tinangkung Utara',
'Totikum (Totikung)',
'Totikum Selatan',
'Biau',
'Bokat',
'Bukal',
'Bunobogu',
'Gadung',
'Karamat',
'Lipunoto',
'Momunu',
'Paleleh',
'Paleleh Barat',
'Tiloan',
'Balaesang',
'Banawa Selatan',
'Banawa Tengah',
'Damsol (Dampelas Sojol)',
'Labuan',
'Pinembani',
'Rio Pakava (Riopakawa)',
'Sindue',
'Sindue Tobata',
'Sindue Tombusabora',
'Sirenja',
'Sojol',
'Sojol Utara',
'Tanantovea',
'Bahodopi',
'Bumi Raya',
'Bungku Barat',
'Bungku Selatan',
'Bungku Tengah',
'Bungku Utara',
'Lembo',
'Mamosalato',
'Menui Kepulauan',
'Mori Atas',
'Petasia',
'Soyo Jaya',
'Wita Ponda',
'Ampibabo',
'Balinggi',
'Bolano Lambunu',
'Kasimbar',
'Mepanga',
'Moutong',
'Palasa',
'Parigi Barat',
'Parigi Selatan',
'Parigi Tengah',
'Parigi Utara',
'Sausu',
'Siniu',
'Taopa',
'Tinombo',
'Tinombo Selatan',
'Tomini',
'Toribulu',
'Torue',
'Lage',
'Lore Barat',
'Lore Piore',
'Lore Selatan',
'Lore Tengah',
'Lore Timur',
'Lore Utara',
'Pamona Barat',
'Pamona Selatan',
'Pamona Tenggara',
'Pamona Timur',
'Pamona Utara',
'Poso Kota Selatan',
'Poso Kota Utara',
'Poso Pesisir',
'Poso Pesisir Selatan',
'Poso Pesisir Utara',
'Dolo',
'Dolo Barat',
'Dolo Selatan',
'Gumbasa',
'Kinovaru',
'Kulawi',
'Kulawi Selatan',
'Lindu',
'Marawola',
'Marawola Barat',
'Nokilalaki',
'Palolo',
'Pipikoro',
'Sigi Biromaru',
'Tanambulava',
'Ampana Tete',
'Togean',
'Tojo',
'Tojo Barat',
'Ulu Bongka',
'Una - Una',
'Walea Besar',
'Walea Kepulauan',
'Baolan',
'Basidondo',
'Dako Pamean',
'Dampal Selatan',
'Dampal Utara',
'Dondo',
'Galang',
'Lampasio',
'Ogo Deide',
'Tolitoli Utara',
'Palu Barat',
'Palu Selatan',
'Palu Timur',
'Palu Utara',
'Kabaena',
'Kabaena Barat',
'Kabaena Selatan',
'Kabaena Tengah',
'Kabaena Timur',
'Kabaena Utara',
'Kepulauan Masaloka Raya',
'Lentarai Jaya S. (Lantari Jaya)',
'Mata Oleo',
'Mata Usu',
'Poleang',
'Poleang Barat',
'Poleang Selatan',
'Poleang Tengah',
'Poleang Tenggara',
'Poleang Timur',
'Poleang Utara',
'Rarowatu',
'Rarowatu Utara',
'Rumbia Tengah',
'Tontonunu (Tontonuwu)',
'Batauga',
'Batu Atas',
'Kadatua',
'Kapontori',
'Lakudo',
'Lasalimu',
'Lasalimu Selatan',
'Mawasangka',
'Mawasangka Timur',
'Sampolawa',
'Siompu',
'Talaga Raya (Telaga Raya)',
'Bonegunu',
'Kambowa',
'Kulisusu (Kalingsusu/kalisusu)',
'Kulisusu Barat',
'Kulisusu Utara',
'Wakorumba Utara',
'Uluiwoi',
'Batu Putih',
'Andoolo',
'Angata',
'Baito',
'Basala',
'Benua',
'Buke',
'Kolono',
'Konda',
'Laeya',
'Lainea',
'Lalumbuu',
'Landono',
'Laonti',
'Moramo',
'Moramo Utara',
'Mowila',
'Palangga',
'Palangga Selatan',
'Ranomeeto',
'Ranomeeto Barat',
'Tinanggea',
'Wolasi',
'Asera',
'Langgikima',
'Lasolo',
'Lembo',
'Molawe',
'Sawa',
'Wiwirano',
'Wakorumba Selatan',
'Binongko',
'Tomia',
'Betoambari',
'Bungi',
'Kokalukuna',
'Murhum',
'Sora Walio (Sorowalio)',
'Wolio',
'Abeli',
'Baruga',
'Kadia',
'Kambu',
'Kendari',
'Kendari Barat',
'Mandonga',
'Poasia',
'Puuwatu',
'Wua-Wua',
'Bilalang',
'Bolaang',
'Bolaang Timur',
'Dumoga Barat',
'Dumoga Timur',
'Dumoga Utara',
'Lolak',
'Lolayan',
'Passi Barat',
'Passi Timur',
'Poigar',
'Sangtombolang',
'Bolaang Uki',
'Pinolosian',
'Pinolosian Tengah',
'Pinolosian Timur',
'Posigadan',
'Kotabunan',
'Modayag',
'Modayag Barat',
'Nuangan',
'Tutuyan',
'Bintauna',
'Bolang Itang Barat',
'Bolang Itang Timur',
'Kaidipang',
'Pinogaluman',
'Sangkub',
'Kendahe',
'Manganitu',
'Manganitu Selatan',
'Nusa Tabukan',
'Tabukan Selatan',
'Tabukan Selatan Tengah',
'Tabukan Selatan Tenggara',
'Tabukan Tengah',
'Tabukan Utara',
'Tahuna Barat',
'Tahuna Timur',
'Tamako',
'Tatoareng',
'Biaro',
'Siau Barat',
'Siau Barat Selatan',
'Siau Barat Utara',
'Siau Tengah',
'Siau Timur',
'Siau Timur Selatan',
'Tagulandang',
'Tagulandang Selatan',
'Tagulandang Utara',
'Beo',
'Beo Selatan',
'Beo Utara',
'Damao (Damau)',
'Essang',
'Essang Selatan',
'Gemeh',
'Kabaruan',
'Kalongan',
'Lirung',
'Melonguane',
'Melonguane Timur',
'Miangas',
'Moronge',
'Nanusa',
'Pulutan',
'Rainis',
'Salibabu',
'Tampan Amma',
'Eris',
'Kakas',
'Kawangkoan',
'Kombi',
'Langowan Barat',
'Langowan Selatan',
'Langowan Timur',
'Langowan Utara',
'Lembean Timur',
'Pineleng',
'Remboken',
'Sonder',
'Tombariri',
'Tombulu',
'Tompaso',
'Tondano Barat',
'Tondano Selatan',
'Tondano Timur',
'Tondano Utara',
'Amurang Barat',
'Amurang Timur',
'Kumelembuai',
'Maesaan',
'Modoinding',
'Motoling',
'Motoling Barat',
'Motoling Timur',
'Ranoyapo',
'Sinonsayang',
'Suluun Tareran',
'Tareran',
'Tatapaan',
'Tenga',
'Tompaso Baru',
'Tumpaan',
'Belang',
'Pusomaen',
'Ratatotok',
'Toluaan (Touluaan)',
'Tombatu',
'Dimembe',
'Kalawat',
'Kauditan',
'Kema',
'Likupang Barat',
'Likupang Selatan',
'Likupang Timur',
'Talawaan',
'Wori',
'Aertembaga (Bitung Timur)',
'Girian',
'Lembeh Selatan (Bitung Selatan)',
'Lembeh Utara',
'Madidir (Bitung Tengah)',
'Maesa',
'Matuari (Bitung Barat)',
'Ranowulu (Bitung Utara)',
'Kotamobagu Barat',
'Kotamobagu Selatan',
'Kotamobagu Timur',
'Kotamobagu Utara',
'Bunaken',
'Malalayang',
'Mapanget',
'Sario',
'Singkil',
'Tikala',
'Tuminting',
'Wanea',
'Wenang',
'Tomohon Barat',
'Tomohon Selatan',
'Tomohon Tengah',
'Tomohon Timur',
'Tomohon Utara',
'Ampek Nagari (Iv Nagari)',
'Banuhampu',
'Baso',
'Candung',
'Iv Angkat Candung (Ampek Angkek)',
'Iv Koto (Ampek Koto)',
'Kamang Magek',
'Malakak',
'Matur',
'Palembayan',
'Palupuh',
'Sungai Pua (Puar)',
'Tanjung Mutiara',
'Tanjung Raya',
'Tilatang Kamang',
'Asam Jujuhan',
'Ix Koto',
'Koto Baru',
'Koto Besar',
'Koto Salak',
'Padang Laweh',
'Sitiung',
'Sungai Rumbai',
'Timpeh',
'Tiumang',
'Pagai Selatan',
'Pagai Utara',
'Siberut Barat',
'Siberut Barat Daya',
'Siberut Selatan',
'Siberut Tengah',
'Siberut Utara',
'Sikakap',
'Sipora Selatan',
'Sipora Utara',
'Akabiluru',
'Bukik Barisan',
'Guguak (Gugu)',
'Gunuang Omeh (Gunung Mas)',
'Harau',
'Kapur Ix/sembilan',
'Lareh Sago Halaban',
'Luak (Luhak)',
'Mungka',
'Pangkalan Koto Baru',
'Payakumbuh Kab. Lima Puluh Kota',
'Situjuah Limo/lima Nagari',
'Suliki',
'2 X 11 Enam Lingkung',
'2 X 11 Kayu Tanam',
'Batang Anai',
'Batang Gasan',
'Enam Lingkung',
'Iv Koto Aur Malintang',
'Nan Sabaris',
'Padang Sago',
'Patamuan',
'Sintuk/sintuak Toboh Gadang',
'Sungai Geringging/garingging',
'Sungai Limau',
'Ulakan Tapakih/tapakis',
'V Koto Kampung Dalam',
'V Koto Timur',
'Vii Koto Sungai Sarik',
'Bonjol',
'Duo Koto (Ii Koto)',
'Mapat Tunggul',
'Mapat Tunggul Selatan',
'Padang Gelugur',
'Panti',
'Rao',
'Rao Selatan',
'Rao Utara',
'Simpang Alahan Mati',
'Tigo Nagari (Iii Nagari)',
'Gunung Tuleh',
'Kinali',
'Koto Balingka',
'Lembah Melintang',
'Luhak Nan Duo',
'Pasaman',
'Ranah Batahan',
'Sasak Ranah Pasisir/pesisie',
'Sei Beremas',
'Sungai Aur',
'Talamau',
'Basa Ampek/iv Balai Tapan',
'Batang Kapas',
'Bayang',
'Bayang Utara (Iv Nagari Bayang Utara)',
'Iv Jurai',
'Koto Xi Tarusan',
'Lengayang',
'Linggo Sari Baganti',
'Lunang Silaut',
'Pancung Soal',
'Ranah Pesisir Kab. Pesisir Selatan',
'Sutera',
'Iv Nagari',
'Kamang Baru',
'Koto Vii (Tujuh)',
'Kupitan',
'Lubuk Tarok',
'Sijunjung',
'Sumpur Kudus',
'Tanjung Gadang',
'Bukit Sundi',
'Danau Kembar',
'Gunung Talang',
'Hiliran Gumanti',
'Ix Koto Sungai Lasi',
'Junjung Sirih',
'Kubung',
'Lembah Gumanti',
'Lembang Jaya',
'Pantai Cermin',
'Payung Sekaki',
'Sepuluh/x Koto Diatas',
'Sepuluh/x Koto Singkarak',
'Tigo Lurah Bajanjang',
'Koto Parik Gadang Diateh',
'Pauh Duo',
'Sangir',
'Sangir Balai Janggo',
'Sangir Batang Hari',
'Sangir Jujuan',
'Sungai Pagu',
'Batipuh',
'Batipuh Selatan',
'Lima Kaum',
'Lintau Buo',
'Lintau Buo Utara',
'Padang Ganting',
'Pariangan',
'Rambatan',
'Salimpaung',
'Sepuluh Koto (X Koto)',
'Sungai Tarab',
'Sungayang',
'Tanjung Baru',
'Tanjung Emas',
'Aur Birugo Tigo Baleh',
'Guguk Panjang (Guguak Panjang)',
'Mandiangin Koto Selayan',
'Bungus Teluk Kabung',
'Koto Tangah',
'Kuranji',
'Lubuk Begalung',
'Lubuk Kilangan',
'Nanggalo',
'Padang Barat',
'Padang Selatan',
'Padang Timur',
'Padang Utara',
'Pauh',
'Padang Panjang Barat',
'Padang Panjang Timur',
'Pariaman Selatan',
'Pariaman Tengah',
'Pariaman Utara',
'Lamposi Tigo Nagari',
'Payakumbuh Barat',
'Payakumbuh Selatan',
'Payakumbuh Timur',
'Payakumbuh Utara',
'Barangin',
'Lembah Segar',
'Silungkang',
'Talawi',
'Lubuk Sikarah',
'Tanjung Harapan',
'Air Salek',
'Banyuasin I',
'Banyuasin Ii',
'Banyuasin Iii',
'Betung',
'Makarti Jaya',
'Muara Padang',
'Muara Sugihan',
'Muara Telang',
'Pulau Rimau',
'Rambutan',
'Rantau Bayur',
'Talang Kelapa',
'Tanjung Lago',
'Tungkal Ilir',
'Lintang Kanan',
'Muara Pinang',
'Pasemah Air Keruh',
'Pendopo',
'Talang Padang',
'Ulu Musi',
'Gumay Talang',
'Jarai',
'Kikim Barat',
'Kikim Selatan',
'Kikim Tengah',
'Kikim Timur',
'Kota Agung',
'Merapi Barat',
'Merapi Timur',
'Mulak Ulu',
'Pagar Gunung',
'Pajar Bulan',
'Pseksu',
'Pulau Pinang',
'Tanjung Sakti Pumi',
'Tanjung Sakti Pumu',
'Abab',
'Benakat',
'Gelumbang',
'Gunung Megang',
'Kelekar',
'Lembak',
'Lubai',
'Muara Belida',
'Penukal (Penukal Abab)',
'Penukal Utara',
'Rambang',
'Rambang Dangku',
'Semendo Darat Laut',
'Semendo Darat Tengah',
'Semendo Darat Ulu',
'Sungai Rotan',
'Talang Ubi',
'Tanah Abang',
'Tanjung Agung',
'Ujan Mas',
'Babat Toman',
'Batanghari Leko',
'Bayung Lencir',
'Keluang',
'Lais',
'Lalan (Sungai Lalan)',
'Plakat Tinggi (Pelakat Tinggi)',
'Sanga Desa',
'Sungai Keruh',
'Batukuning Lakitan Ulu (Bts)/cecar',
'Jaya Loka',
'Karang Dapo',
'Karang Jaya',
'Megang Sakti',
'Muara Beliti',
'Muara Kelingi',
'Muara Lakitan',
'Nibung',
'Purwodadi',
'Rawas Ilir',
'Rawas Ulu',
'Rupit',
'Selangit',
'Stl Ulu Terawas',
'Sukakarya',
'Sumber Harta',
'Tiang Pumpung Kepungut',
'Tuah Negeri',
'Tugumulyo',
'Ulu Rawas',
'Indralaya Selatan',
'Indralaya Utara',
'Kandis',
'Lubuk Keliat',
'Muara Kuang',
'Payaraman',
'Pemulutan',
'Pemulutan Barat',
'Pemulutan Selatan',
'Rambang Kuang',
'Rantau Alai',
'Rantau Panjang',
'Sungai Pinang',
'Tanjung Batu',
'Tanjung Raja',
'Air Sugihan',
'Cengal',
'Jejawi',
'Lempuing',
'Lempuing Jaya',
'Mesuji',
'Mesuji Makmur',
'Mesuji Raya',
'Pampangan',
'Pangkalan Lampam',
'Pedamaran',
'Pedamaran Timur',
'Sirah Pulau Padang',
'Sungai Menang',
'Tanjung Lubuk',
'Teluk Gelam',
'Tulung Selapan',
'Lengkiti',
'Lubuk Batang',
'Lubuk Raja',
'Pengandonan',
'Peninjauan',
'Semidang Aji',
'Sinar Peninjauan',
'Sosoh Buay Rayap',
'Ulu Ogan',
'Banding Agung',
'Buana Pemaca',
'Buay Pemaca',
'Buay Pematang Ribu Ranau Tengah',
'Buay Rawan',
'Buay Runjung',
'Buay Sandang Aji',
'Kisam Ilir',
'Kisam Tinggi',
'Mekakau Ilir',
'Muaradua Kisam',
'Pulau Beringin',
'Runjung Agung',
'Simpang',
'Sindang Danau',
'Sungai Are',
'Tiga Dihaji',
'Warkuk Ranau Selatan',
'Belitang I',
'Belitang Ii',
'Belitang Iii',
'Belitang Jaya',
'Belitang Madang Raya',
'Belitang Mulya',
'Buay Madang',
'Buay Madang Timur',
'Buay Pemuka Bangsa Raja',
'Buay Pemuka Beliung',
'Bunga Mayang',
'Cempaka',
'Jayapura',
'Madang Suku I',
'Madang Suku Ii',
'Madang Suku Iii',
'Semendawai Barat',
'Semendawai Suku Iii',
'Semendawai Timur',
'Lubuk Linggau Barat I',
'Lubuk Linggau Barat Ii',
'Lubuk Linggau Selatan I',
'Lubuk Linggau Selatan Ii',
'Lubuk Linggau Timur I',
'Lubuk Linggau Timur Ii',
'Lubuk Linggau Utara I',
'Lubuk Linggau Utara Ii',
'Dempo Selatan',
'Dempo Tengah',
'Dempo Utara',
'Pagar Alam Selatan',
'Pagar Alam Utara',
'Alang-Alang Lebar',
'Bukit Kecil',
'Gandus',
'Ilir Barat I',
'Ilir Barat Ii',
'Ilir Timur I',
'Ilir Timur Ii',
'Kalidoni',
'Kemuning',
'Kertapati',
'Plaju',
'Sako',
'Seberang Ulu I',
'Seberang Ulu Ii',
'Sematang Borang',
'Sukarame Palembang',
'Cambai',
'Prabumulih Barat',
'Prabumulih Selatan',
'Prabumulih Timur',
'Prabumulih Utara',
'Rambang Kapak Tengah',
'Aek Kuasan',
'Aek Ledong',
'Aek Songsongan',
'Air Batu',
'Air Joman',
'Bandar Pasir Mandoge',
'Bandar Pulau',
'Buntu Pane',
'Meranti',
'Pulau Rakyat',
'Pulo Bandring',
'Rahuning',
'Rawang Panca Arga',
'Sei Dadap',
'Sei Kepayang',
'Sei Kepayang Barat',
'Sei Kepayang Timur',
'Setia Janji',
'Silau Laut',
'Simpang Empat',
'Tanjung Balai',
'Teluk Dalam',
'Tinggi Raja',
'Air Putih',
'Limapuluh',
'Medang Deras',
'Sei Balai',
'Sei Suka',
'Talawi',
'Tanjung Tiram',
'Berampu (Brampu)',
'Gunung Sitember',
'Lae Parira',
'Parbuluan',
'Pegagan Hilir',
'Siempat Nempu',
'Siempat Nempu Hilir',
'Siempat Nempu Hulu',
'Silahi Sabungan',
'Silima Pungga-Pungga',
'Sitinjo',
'Sumbul',
'Tanah Pinem',
'Tiga Lingga',
'Bangun Purba',
'Batang Kuis',
'Beringin',
'Biru-Biru',
'Deli Tua',
'Galang',
'Gunung Meriah',
'Hamparan Perak',
'Kutalimbaru',
'Labuhan Deli',
'Namo Rambe',
'Pagar Merbau',
'Pancur Batu',
'Pantai Labu',
'Patumbak',
'Percut Sei Tuan',
'Sibolangit',
'Sinembah Tanjung Muda Hilir',
'Sinembah Tanjung Muda Hulu',
'Sunggal',
'Bakti Raja',
'Dolok Sanggul',
'Lintong Nihuta',
'Onan Ganjang',
'Pakkat',
'Paranginan',
'Parlilitan',
'Pollung',
'Sijama Polang',
'Tara Bintang',
'Barus Jahe',
'Brastagi (Berastagi)',
'Dolat Rayat',
'Juhar',
'Kuta Buluh',
'Laubaleng',
'Mardinding',
'Merdeka',
'Merek',
'Munte',
'Nama Teran',
'Payung',
'Simpang Empat',
'Tiga Binanga',
'Tiga Panah',
'Tiganderket',
'Panai Hilir',
'Panai Hulu',
'Panai Tengah',
'Kampung Rakyat',
'Kota Pinang',
'Sei/sungai Kanan',
'Silangkitang',
'Torgamba',
'Aek Kuo',
'Aek Natas',
'Kuala Ledong (Kualuh Leidong)',
'Kualuh Hilir',
'Kualuh Hulu',
'Kualuh Selatan',
'Marbau',
'Na Ix-X',
'Babalan',
'Bahorok',
'Batang Serangan',
'Besitang',
'Binjai',
'Brandan Barat',
'Gebang',
'Hinai',
'Kuala',
'Kutambaru',
'Padang Tualang',
'Pangkalan Susu',
'Pematang Jaya',
'Salapian',
'Sawit Seberang',
'Secanggang',
'Sei Binge (Bingai)',
'Sei Lepan',
'Selesai',
'Sirapit (Serapit)',
'Tanjung pura',
'Wampu',
'Batahan',
'Batang Natal',
'Bukit Malintang',
'Huta Bargot',
'Kotanopan',
'Langga Bayu (Lingga Bayu)',
'Lembah Sorik Merapi',
'Muara Batang Gadis',
'Muara Sipongi',
'Naga Juang',
'Natal',
'Pakantan',
'Panyabungan Barat',
'Panyabungan Kota',
'Panyabungan Selatan',
'Panyabungan Timur',
'Panyabungan Utara',
'Puncak Sorik Marapi/merapi',
'Ranto Baek/baik',
'Siabu',
'Sinunukan',
'Tambangan',
'Ulu Pungkut',
'Bawolato',
'Botomuzoi',
'Gido',
'Hili Serangkai (Hilisaranggu)',
'Hiliduho',
'Idano Gawo',
'Ma\'u',
'Somolo-Molo (Samolo)',
'Ulugawo',
'Lahomi (Gahori)',
'Lolofitu Moi',
'Mandrehe',
'Mandrehe Barat',
'Mandrehe Utara',
'Moro\'o',
'Sirombu',
'Ulu Moro\'o (Ulu Narwo)',
'Amandraya',
'Gomo',
'Hibala',
'Lahusa',
'Lolomatua',
'Lolowau',
'Pulau-Pulau Batu',
'Afulu',
'Alasa',
'Alasa Talumuzoi',
'Lahewa',
'Lahewa Timur',
'Lotu',
'Namohalu Esiwa',
'Sawo',
'Sitolu Ori',
'Tugala Oyo',
'Tuhemberua',
'Barumun',
'Barumun Tengah',
'Batang Lubu Sutam',
'Huristak',
'Huta Raja Tinggi',
'Lubuk Barumun',
'Sosa',
'Sosopan',
'Ulu Barumun',
'Batang Onang',
'Dolok',
'Dolok Sigompulon',
'Halongonan',
'Hulu Sihapas',
'Padang Bolak',
'Padang Bolak Julu',
'Portibi',
'Simangambat',
'Kerajaan',
'Pagindar',
'Pergetteng-Getteng Sengkut',
'Salak',
'Siempat Rube',
'Sitellu Tali Urang Jehe',
'Sitellu Tali Urang Julu',
'Tinada',
'Harian',
'Nainggolan',
'Onan Runggu',
'Palipi',
'Ronggur Nihuta',
'Sianjur Mula-Mula',
'Simanindo',
'Sitio-Tio',
'Bandar Khalifah',
'Bintang Bayu',
'Dolok Masihul',
'Dolok Merawan',
'Kotarih',
'Pantai Cermin',
'Pegajahan',
'Perbaungan',
'Sei Bamban',
'Serba Jadi/Lokop',
'Silinda',
'Sipispis',
'Tanjung Beringin',
'Tebing Syahbandar',
'Tebing Tinggi',
'Teluk Mengkudu',
'Bandar',
'Bandar Huluan',
'Bandar Masilam',
'Bosar Maligas',
'Dolok Batu Nanggar',
'Dolok Panribuan',
'Dolok Pardamean',
'Dolok Silau',
'Girsang Sipangan Bolon',
'Gunung Malela',
'Gunung Maligas',
'Haranggaol Horison',
'Hatonduhan',
'Huta Bayu Raja',
'Jawa Maraja Bah Jambi',
'Jorlang Hataran',
'Panei',
'Panombeian Panei',
'Pematang Bandar',
'Pematang Sidamanik',
'Pematang Silima Huta',
'Purba',
'Raya',
'Raya Kahean',
'Siantar',
'Sidamanik',
'Silimakuta',
'Silou Kahean',
'Tanah Jawa',
'Tapian Dolok',
'Ujung Padang',
'Aek Bilah',
'Angkola Barat (Padang Sidempuan)',
'Angkola Timur (Padang Sidempuan)',
'Arse',
'Batang Angkola',
'Batang Toru',
'Marancar',
'Saipar Dolok Hole',
'Sayur Matinggi',
'Siais',
'Andam Dewi',
'Badiri',
'Barus',
'Barus Utara',
'Kolang',
'Lumut',
'Manduamas',
'Pandan',
'Pasaribu Tobing',
'Pinangsori',
'Sarudik',
'Sibabangun',
'Sitahuis',
'Sorkam',
'Sorkam Barat',
'Sosor Gadong',
'Suka Bangun',
'Tapian Nauli',
'Tukka',
'Adian Koting',
'Garoga',
'Muara',
'Pagaran',
'Pahae Jae',
'Pahae Julu',
'Pangaribuan',
'Parmonangan',
'Purbatua',
'Siatas Barita',
'Simangumban',
'Sipahutar',
'Sipoholon',
'Ajibata',
'Bor-Bor',
'Habinsaran',
'Lagu boti',
'Lumban Julu',
'Nassau',
'Pintu Pohan Meranti',
'Porsea',
'Siantar Narumonda',
'Sigumpar',
'Silaen',
'Tampahan',
'Uluan',
'Binjai Barat',
'Binjai Kota',
'Binjai Selatan',
'Binjai Timur',
'Binjai Utara',
'Gunung sitoli',
'Gunungsitoli Alo\'oa',
'Gunungsitoli Barat',
'Gunungsitoli Idanoi',
'Gunungsitoli Selatan',
'Gunungsitoli Utara',
'Medan Amplas',
'Medan Area',
'Medan Barat',
'Medan Baru',
'Medan Belawan Kota',
'Medan Deli',
'Medan Denai',
'Medan Helvetia',
'Medan Johor',
'Medan Kota',
'Medan Labuhan',
'Medan Maimun',
'Medan Marelan',
'Medan Perjuangan',
'Medan Petisah',
'Medan Polonia',
'Medan Selayang',
'Medan Sunggal',
'Medan Tembung',
'Medan Timur',
'Medan Tuntungan',
'Padang Sidempuan Angkola Julu',
'Padang Sidempuan Batu nadua',
'Padang Sidempuan Hutaimbaru',
'Padang Sidempuan Selatan',
'Padang Sidempuan Tenggara',
'Padang Sidempuan Utara',
'Siantar Barat',
'Siantar Marihat',
'Siantar Martoba',
'Siantar Selatan',
'Siantar Timur',
'Siantar Utara',
'Sibolga Kota',
'Sibolga Sambas',
'Sibolga Selatan',
'Sibolga Utara',
'Datuk Bandar',
'Datuk Bandar Timur',
'Sei Tualang Raso',
'Tanjung Balai Selatan',
'Tanjung Balai Utara',
'Teluk Nibung',
'Bajenis',
'Padang Hilir',
'Padang Hulu',
'Rambutan',
'Tebing Tinggi Medan')